import "Aniversario.dart";
class AniversarioList {
  static List <Aniversario> lista= [
      Aniversario(DateTime(2025, 4, 1), 'Ama fotografia de paisagens','Ana Silveira'),
Aniversario(DateTime(2025, 4, 1), 'Ama fotografia de paisagens','Ana Biqueira'),
Aniversario(DateTime(2025, 4, 2), 'Fã de documentários','Bruno Teixeira'),
Aniversario(DateTime(2025, 4, 3), 'Gosta de culinária vegana','Carla Nogueira'),
Aniversario(DateTime(2025, 4, 4), 'Ama esportes radicais','Diego Souza'),
Aniversario(DateTime(2025, 4, 5), 'Curte plantas raras','Elisa Fernandes'),
Aniversario(DateTime(2025, 4, 6), 'Fã de astronomia','Fábio Torres'),
Aniversario(DateTime(2025, 4, 7), 'Ama escultura','Gabriela Mello'),
Aniversario(DateTime(2025, 4, 8), 'Fã de jogos indie','Henrique Diniz'),
Aniversario(DateTime(2025, 4, 9), 'Gosta de meditação','Isabel Correia'),
Aniversario(DateTime(2025, 4, 10), 'Ama cozinhar churrasco','João Barros'),
Aniversario(DateTime(2025, 4, 11), 'Curte moda sustentável','Karla Fontes'),
Aniversario(DateTime(2025, 4, 12), 'Fã de kart','Leonardo Mendes'),
Aniversario(DateTime(2025, 4, 13), 'Gosta de costura','Marina Cardoso'),
Aniversario(DateTime(2025, 4, 14), 'Fã de jazz','Nicolas Brito'),
Aniversario(DateTime(2025, 4, 15), 'Ama arquitetura','Olívia Sales'),
Aniversario(DateTime(2025, 4, 16), 'Fã de drones','Pedro Leal'),
Aniversario(DateTime(2025, 4, 17), 'Gosta de dança clássica','Quitéria Lopes'),
Aniversario(DateTime(2025, 4, 18), 'Curte astronomia','Renan Lima'),
Aniversario(DateTime(2025, 4, 19), 'Ama papelaria','Sabrina Pires'),
Aniversario(DateTime(2025, 4, 20), 'Fã de esportes','Thiago Amaral'),
Aniversario(DateTime(2025, 4, 21), 'Curte música clássica','Úrsula Soares'),
Aniversario(DateTime(2025, 4, 22), 'Ama pets','Vagner Bezerra'),
Aniversario(DateTime(2025, 4, 23), 'Gosta de gastronomia','Wanda Teles'),
Aniversario(DateTime(2025, 4, 24), 'Fã de tecnologia retrô','Xisto Azevedo'),
Aniversario(DateTime(2025, 4, 25), 'Curte samba','Yara Campos'),
Aniversario(DateTime(2025, 4, 26), 'Ama vinhos','Zacarias Rocha'),
Aniversario(DateTime(2025, 4, 27), 'Fã de literatura russa','Aline Figueiredo'),
Aniversario(DateTime(2025, 4, 28), 'Gosta de alpinismo','Breno Assunção'),
Aniversario(DateTime(2025, 4, 29), 'Fã de tecnologia','Camila Xavier'),
Aniversario(DateTime(2025, 4, 30), 'Curte mixologia','Daniel Guimarães'),
Aniversario(DateTime(2025, 3, 1), 'Gosta de pesca', 'Arthur Ramos'),
Aniversario(DateTime(2025, 3, 2), 'Ama culinária francesa', 'Bia Albuquerque'),
Aniversario(DateTime(2025, 3, 3), 'Fã de trilhas', 'Carlos Sampaio'),
Aniversario(DateTime(2025, 3, 4), 'Gosta de astrologia', 'Duda Vasconcelos'),
Aniversario(DateTime(2025, 3, 5), 'Ama jardinagem', 'Eduardo Pinheiro'),
Aniversario(DateTime(2025, 3, 6), 'Curte esportes aquáticos', 'Fernanda Melo'),
Aniversario(DateTime(2025, 3, 7), 'Fã de ficção científica', 'Gustavo Reis'),
Aniversario(DateTime(2025, 3, 8), 'Gosta de pintura', 'Helena Dias'),
Aniversario(DateTime(2025, 3, 9), 'Ama cinema europeu', 'Igor Farias'),
Aniversario(DateTime(2025, 3, 10), 'Coleciona moedas', 'Juliana Torres'),
Aniversario(DateTime(2025, 3, 11), 'Fã de culinária mexicana', 'Kevin Rocha'),
Aniversario(DateTime(2025, 3, 12), 'Gosta de astronomia', 'Lara Matos'),
Aniversario(DateTime(2025, 3, 13), 'Curte marcenaria', 'Mateus Braga'),
Aniversario(DateTime(2025, 3, 14), 'Ama bordado', 'Nina Cunha'),
Aniversario(DateTime(2025, 3, 15), 'Gosta de patinação', 'Oscar Peixoto'),
Aniversario(DateTime(2025, 3, 16), 'Fã de moda vintage', 'Patrícia Gomes'),
Aniversario(DateTime(2025, 3, 17), 'Ama violão', 'Rafael Monteiro'),
Aniversario(DateTime(2025, 3, 18), 'Gosta de yoga', 'Sara Martins'),
Aniversario(DateTime(2025, 3, 19), 'Fã de séries', 'Tiago Duarte'),
Aniversario(DateTime(2025, 3, 20), 'Ama natureza', 'Úrsula Lima'),
Aniversario(DateTime(2025, 3, 21), 'Fã de basquete', 'Victor Oliveira'),
Aniversario(DateTime(2025, 3, 22), 'Gosta de danças latinas', 'Wendy Pacheco'),
Aniversario(DateTime(2025, 3, 23), 'Ama trilhas', 'Xander Campos'),
Aniversario(DateTime(2025, 3, 24), 'Fã de design gráfico', 'Yasmin Barros'),
Aniversario(DateTime(2025, 3, 25), 'Curte aromaterapia', 'Zara Rodrigues'),
Aniversario(DateTime(2025, 3, 26), 'Ama fotografia', 'Abel Furtado'),
Aniversario(DateTime(2025, 3, 27), 'Gosta de leitura clássica', 'Beatriz Alves'),
Aniversario(DateTime(2025, 3, 28), 'Fã de rock', 'Caio Moreira'),
Aniversario(DateTime(2025, 3, 29), 'Ama origami', 'Daniela Rocha'),
Aniversario(DateTime(2025, 3, 30), 'Curte aventuras', 'Eduarda Nunes'),
Aniversario(DateTime(2025, 3, 31), 'Fã de futebol', 'Fábio Mendes'),
Aniversario(DateTime(2025, 3, 31), 'Fã de futebol', 'Fábio Mendes'),
Aniversario(DateTime(2025, 2, 1), 'Ama flores e poesia', 'Ana Paula'),
Aniversario(DateTime(2025, 2, 2), 'Fã de esportes radicais', 'Bruno Lima'),
Aniversario(DateTime(2025, 2, 3), 'Gosta de cozinhar', 'Carla Souza'),
Aniversario(DateTime(2025, 2, 4), 'Apreciador de vinho', 'Diego Torres'),
Aniversario(DateTime(2025, 2, 5), 'Ama gatos', 'Elisa Martins'),
Aniversario(DateTime(2025, 2, 6), 'Coleciona action figures', 'Fábio Rocha'),
Aniversario(DateTime(2025, 2, 7), 'Ama fotografia', 'Gabriela Dias'),
Aniversario(DateTime(2025, 2, 8), 'Curte videogames', 'Henrique Alves'),
Aniversario(DateTime(2025, 2, 9), 'Fã de música clássica', 'Isabela Pires'),
Aniversario(DateTime(2025, 2, 10), 'Ama futebol', 'João Pedro'),
Aniversario(DateTime(2025, 2, 11), 'Curte astrologia', 'Karla Monteiro'),
Aniversario(DateTime(2025, 2, 12), 'Ama livros de ficção', 'Leonardo Vieira'),
Aniversario(DateTime(2025, 2, 13), 'Gosta de plantas', 'Marina Freitas'),
Aniversario(DateTime(2025, 2, 14), 'Fã de animes', 'Nicolas Duarte'),
Aniversario(DateTime(2025, 2, 15), 'Ama yoga', 'Olívia Ramos'),
Aniversario(DateTime(2025, 2, 16), 'Gosta de astronomia', 'Paulo César'),
Aniversario(DateTime(2025, 2, 17), 'Curte arte moderna', 'Quitéria Lopes'),
Aniversario(DateTime(2025, 2, 18), 'Gosta de trilhas', 'Rafael Nogueira'),
Aniversario(DateTime(2025, 2, 19), 'Ama maquiagem', 'Sabrina Teixeira'),
Aniversario(DateTime(2025, 2, 20), 'Fã de tecnologia', 'Tiago Fonseca'),
Aniversario(DateTime(2025, 2, 21), 'Ama natureza', 'Úrsula Silva'),
Aniversario(DateTime(2025, 2, 22), 'Coleciona moedas', 'Victor Hugo'),
Aniversario(DateTime(2025, 2, 23), 'Gosta de artesanato', 'Wanda Santos'),
Aniversario(DateTime(2025, 2, 24), 'Fã de ficção científica', 'Xavier Campos'),
Aniversario(DateTime(2025, 2, 25), 'Ama dança', 'Yasmin Oliveira'),
Aniversario(DateTime(2025, 2, 26), 'Gosta de café', 'Zeca Barreto'),
Aniversario(DateTime(2025, 2, 27), 'Ama cinema', 'Aline Costa'),
Aniversario(DateTime(2025, 2, 28), 'Curte culinária japonesa', 'Bernardo Luz'),
Aniversario(DateTime(2025, 1, 1), 'Gosta de caminhar na praia', 'Alice Carvalho'),
Aniversario(DateTime(2025, 1, 2), 'Ama carros antigos', 'Beto Andrade'),
Aniversario(DateTime(2025, 1, 3), 'Fã de filmes de ação', 'Clara Lima'),
Aniversario(DateTime(2025, 1, 4), 'Coleciona selos', 'Daniel Moura'),
Aniversario(DateTime(2025, 1, 5), 'Ama patinação', 'Erika Tavares'),
Aniversario(DateTime(2025, 1, 6), 'Toca violão', 'Felipe Sanches'),
Aniversario(DateTime(2025, 1, 7), 'Fã de café', 'Giovana Castro'),
Aniversario(DateTime(2025, 1, 8), 'Curte mergulho', 'Heitor Souza'),
Aniversario(DateTime(2025, 1, 9), 'Gosta de moda', 'Ivana Rocha'),
Aniversario(DateTime(2025, 1, 10), 'Ama ciclismo', 'Joel Mendes'),
Aniversario(DateTime(2025, 1, 11), 'Fã de arte japonesa', 'Karine Luz'),
Aniversario(DateTime(2025, 1, 12), 'Curte trilhas', 'Lucas Freitas'),
Aniversario(DateTime(2025, 1, 13), 'Ama astronomia', 'Marcela Guedes'),
Aniversario(DateTime(2025, 1, 14), 'Gosta de mágica', 'Nilo Prado'),
Aniversario(DateTime(2025, 1, 15), 'Curte natação', 'Olga Martins'),
Aniversario(DateTime(2025, 1, 16), 'Ama pintura', 'Paulo Viana'),
Aniversario(DateTime(2025, 1, 17), 'Fã de podcasts', 'Quênia Silveira'),
Aniversario(DateTime(2025, 1, 18), 'Gosta de jardinagem', 'Rafaela Mourão'),
Aniversario(DateTime(2025, 1, 19), 'Ama basquete', 'Samuel Reis'),
Aniversario(DateTime(2025, 1, 20), 'Fã de cinema antigo', 'Tânia Meireles'),
Aniversario(DateTime(2025, 1, 21), 'Gosta de vinil', 'Ulysses Lopes'),
Aniversario(DateTime(2025, 1, 22), 'Ama esportes aquáticos', 'Valéria Gomes'),
Aniversario(DateTime(2025, 1, 23), 'Gosta de tecnologia', 'Willian Costa'),
Aniversario(DateTime(2025, 1, 24), 'Fã de dança', 'Xuxa Ferreira'),
Aniversario(DateTime(2025, 1, 25), 'Curte teatro', 'Yasmin Duarte'),
Aniversario(DateTime(2025, 1, 26), 'Ama carros de corrida', 'Zico Amaral'),
Aniversario(DateTime(2025, 1, 27), 'Fã de culinária italiana', 'Aline Matos'),
Aniversario(DateTime(2025, 1, 28), 'Gosta de história', 'Bernardo Nery'),
Aniversario(DateTime(2025, 1, 29), 'Ama jogos de tabuleiro', 'Carol Ribeiro'),
Aniversario(DateTime(2025, 1, 30), 'Fã de cervejas artesanais', 'Douglas Rocha'),
Aniversario(DateTime(2025, 1, 31), 'Ama astronomia', 'Emília Barreto'),
Aniversario(DateTime(2025, 5, 1), 'Ama fotografia urbana', 'Aline Barbosa'),
Aniversario(DateTime(2025, 5, 2), 'Fã de RPG', 'Bernardo Torres'),
Aniversario(DateTime(2025, 5, 3), 'Curte plantas suculentas', 'Caroline Farias'),
Aniversario(DateTime(2025, 5, 4), 'Ama ciclismo', 'Diego Nascimento'),
Aniversario(DateTime(2025, 5, 5), 'Fã de mitologia', 'Elena Braga'),
Aniversario(DateTime(2025, 5, 6), 'Gosta de chá', 'Fabiana Cunha'),
Aniversario(DateTime(2025, 5, 7), 'Curte caminhadas', 'Gustavo Ramos'),
Aniversario(DateTime(2025, 5, 8), 'Ama costura criativa', 'Helena Duarte'),
Aniversario(DateTime(2025, 5, 9), 'Fã de tênis', 'Ian Peixoto'),
Aniversario(DateTime(2025, 5, 10), 'Curte astrologia', 'Jéssica Oliveira'),
Aniversario(DateTime(2025, 5, 11), 'Gosta de escrita', 'Kaique Martins'),
Aniversario(DateTime(2025, 5, 12), 'Ama cinema nacional', 'Laura Ferreira'),
Aniversario(DateTime(2025, 5, 13), 'Fã de robótica', 'Matheus Reis'),
Aniversario(DateTime(2025, 5, 14), 'Gosta de praia', 'Natália Souza'),
Aniversario(DateTime(2025, 5, 15), 'Ama fotografia analógica', 'Otávio Araújo'),
Aniversario(DateTime(2025, 5, 16), 'Fã de decoração', 'Paula Antunes'),
Aniversario(DateTime(2025, 5, 17), 'Curte trilhas', 'Rafael Tavares'),
Aniversario(DateTime(2025, 5, 18), 'Ama doces caseiros', 'Sandra Dias'),
Aniversario(DateTime(2025, 5, 19), 'Fã de skate', 'Túlio Rocha'),
Aniversario(DateTime(2025, 5, 20), 'Gosta de yoga', 'Úrsula Mendes'),
Aniversario(DateTime(2025, 5, 21), 'Ama puzzles', 'Vítor Almeida'),
Aniversario(DateTime(2025, 5, 22), 'Fã de vinil', 'Wanda Pinto'),
Aniversario(DateTime(2025, 5, 23), 'Gosta de drones', 'Xavier Gomes'),
Aniversario(DateTime(2025, 5, 24), 'Ama dança urbana', 'Yasmin Ribeiro'),
Aniversario(DateTime(2025, 5, 25), 'Curte fotografia noturna', 'Zuleika Costa'),
Aniversario(DateTime(2025, 5, 26), 'Fã de cinema noir', 'Alberto Lima'),
Aniversario(DateTime(2025, 5, 27), 'Gosta de astronomia', 'Bianca Vasconcelos'),
Aniversario(DateTime(2025, 5, 28), 'Curte grafite', 'Caio Medeiros'),
Aniversario(DateTime(2025, 5, 29), 'Fã de maquiagem artística', 'Daniela Loureiro'),
Aniversario(DateTime(2025, 5, 30), 'Gosta de astronomia', 'Edson Carvalho'),
Aniversario(DateTime(2025, 5, 31), 'Ama aprender línguas', 'Fernanda Rangel'),
Aniversario(DateTime(2025, 6, 1), 'Gosta de jardinagem', 'Ana Morais'),
Aniversario(DateTime(2025, 6, 2), 'Curte escalada', 'Bruno Prado'),
Aniversario(DateTime(2025, 6, 3), 'Ama literatura de suspense', 'Carla Ribeiro'),
Aniversario(DateTime(2025, 6, 4), 'Fã de esportes aquáticos', 'Daniel Simões'),
Aniversario(DateTime(2025, 6, 5), 'Curte crochê', 'Elisa Goulart'),
Aniversario(DateTime(2025, 6, 6), 'Gosta de programação', 'Fábio Andrade'),
Aniversario(DateTime(2025, 6, 7), 'Ama dança contemporânea', 'Giovana Lira'),
Aniversario(DateTime(2025, 6, 8), 'Fã de astronomia', 'Heitor Castro'),
Aniversario(DateTime(2025, 6, 9), 'Curte moda vintage', 'Isabela Dias'),
Aniversario(DateTime(2025, 6, 10), 'Gosta de tocar violão', 'João Batista'),
Aniversario(DateTime(2025, 6, 11), 'Fã de arte digital', 'Karine Novaes'),
Aniversario(DateTime(2025, 6, 12), 'Ama futebol', 'Lucas Moraes'),
Aniversario(DateTime(2025, 6, 13), 'Gosta de cozinhar doces', 'Marina Rocha'),
Aniversario(DateTime(2025, 6, 14), 'Curte skate', 'Nicolas Figueira'),
Aniversario(DateTime(2025, 6, 15), 'Ama literatura romântica', 'Olga Mendonça'),
Aniversario(DateTime(2025, 6, 16), 'Fã de cervejas artesanais', 'Paulo Rezende'),
Aniversario(DateTime(2025, 6, 17), 'Gosta de pintura a óleo', 'Quitéria Vieira'),
Aniversario(DateTime(2025, 6, 18), 'Curte costura criativa', 'Rafaela Neves'),
Aniversario(DateTime(2025, 6, 19), 'Fã de tecnologia', 'Samuel Oliveira'),
Aniversario(DateTime(2025, 6, 20), 'Ama pets', 'Tatiane Martins'),
Aniversario(DateTime(2025, 6, 21), 'Gosta de ciclismo', 'Ulysses Barbosa'),
Aniversario(DateTime(2025, 6, 22), 'Curte decoração japonesa', 'Valéria Duarte'),
Aniversario(DateTime(2025, 6, 23), 'Fã de esportes de inverno', 'Wesley Pires'),
Aniversario(DateTime(2025, 6, 24), 'Ama danças folclóricas', 'Xuxa Nascimento'),
Aniversario(DateTime(2025, 6, 25), 'Curte música eletrônica', 'Yasmin Torres'),
Aniversario(DateTime(2025, 6, 26), 'Gosta de culinária japonesa', 'Zeca Rocha'),
Aniversario(DateTime(2025, 6, 27), 'Fã de jazz', 'Aline Couto'),
Aniversario(DateTime(2025, 6, 28), 'Ama yoga', 'Brenda Castro'),
Aniversario(DateTime(2025, 6, 29), 'Fã de tecnologia retrô', 'Caio Nunes'),
Aniversario(DateTime(2025, 6, 30), 'Curte moda indie', 'Daniela Lemos'),
Aniversario(DateTime(2025, 9, 1), 'Ana Costa', 'Ama fotografia analógica'),
Aniversario(DateTime(2025, 9, 2), 'Bruno Almeida', 'Curte videogames retrô'),
Aniversario(DateTime(2025, 9, 3), 'Carla Souza', 'Fã de moda vintage'),
Aniversario(DateTime(2025, 9, 4), 'Davi Pinto', 'Ama corridas de rua'),
Aniversario(DateTime(2025, 9, 5), 'Elena Farias', 'Curte cerâmica'),
Aniversario(DateTime(2025, 9, 6), 'Fábio Souza', 'Ama acampamento'),
Aniversario(DateTime(2025, 9, 7), 'Giovana Almeida', 'Curte literatura fantástica'),
Aniversario(DateTime(2025, 9, 8), 'Henrique Santos', 'Fã de esportes aquáticos'),
Aniversario(DateTime(2025, 9, 9), 'Isadora Lopes', 'Gosta de tricô'),
Aniversario(DateTime(2025, 9, 10), 'João Costa', 'Fã de história medieval'),
Aniversario(DateTime(2025, 9, 11), 'Karla Tavares', 'Gosta de astronomia'),
Aniversario(DateTime(2025, 9, 12), 'Leo Oliveira', 'Ama desenho digital'),
Aniversario(DateTime(2025, 9, 13), 'Mariana Nunes', 'Curte culinária italiana'),
Aniversario(DateTime(2025, 9, 14), 'Nicolas Martins', 'Fã de escalada'),
Aniversario(DateTime(2025, 9, 15), 'Olívia Barbosa', 'Ama literatura clássica'),
Aniversario(DateTime(2025, 9, 16), 'Pedro Ferreira', 'Fã de futebol'),
Aniversario(DateTime(2025, 9, 17), 'Quitéria Souza', 'Curte jardinagem'),
Aniversario(DateTime(2025, 9, 18), 'Rafael Costa', 'Fã de hip hop'),
Aniversario(DateTime(2025, 9, 19), 'Sofia Almeida', 'Ama yoga'),
Aniversario(DateTime(2025, 9, 20), 'Thiago Lima', 'Gosta de arte urbana'),
Aniversario(DateTime(2025, 9, 21), 'Úrsula Souza', 'Curte esportes radicais'),
Aniversario(DateTime(2025, 9, 22), 'Vítor Pereira', 'Ama cozinhar'),
Aniversario(DateTime(2025, 9, 23), 'Wanda Costa', 'Fã de jazz'),
Aniversario(DateTime(2025, 9, 24), 'Xande Oliveira', 'Gosta de fazer cerveja artesanal'),
Aniversario(DateTime(2025, 9, 25), 'Yasmin Ferreira', 'Ama viajar'),
Aniversario(DateTime(2025, 9, 26), 'Zeca Tavares', 'Curte acampamento'),
Aniversario(DateTime(2025, 9, 27), 'Aline Pereira', 'Ama ciclismo'),
Aniversario(DateTime(2025, 9, 28), 'Brenda Lima', 'Fã de cinema de terror'),
Aniversario(DateTime(2025, 9, 29), 'Caio Souza', 'Gosta de fazer churrasco'),
Aniversario(DateTime(2025, 9, 30), 'Daniela Alves', 'Ama leitura de ficção'),
Aniversario(DateTime(2025, 10, 1), 'Ana Costa', 'Ama pintura em aquarela'),
Aniversario(DateTime(2025, 10, 2), 'Bruno Oliveira', 'Curte música clássica'),
Aniversario(DateTime(2025, 10, 3), 'Carla Martins', 'Fã de culinária vegana'),
Aniversario(DateTime(2025, 10, 4), 'Davi Souza', 'Gosta de skate'),
Aniversario(DateTime(2025, 10, 5), 'Elena Rocha', 'Curte escalada'),
Aniversario(DateTime(2025, 10, 6), 'Fábio Nunes', 'Fã de vinho'),
Aniversario(DateTime(2025, 10, 7), 'Giovana Santos', 'Ama fotografia de rua'),
Aniversario(DateTime(2025, 10, 8), 'Henrique Almeida', 'Curte história medieval'),
Aniversario(DateTime(2025, 10, 9), 'Isadora Lima', 'Ama cozinhar sobremesas'),
Aniversario(DateTime(2025, 10, 10), 'João Costa', 'Fã de videogames'),
Aniversario(DateTime(2025, 10, 11), 'Karla Alves', 'Ama jardinagem'),
Aniversario(DateTime(2025, 10, 12), 'Leo Pereira', 'Curte cinema independente'),
Aniversario(DateTime(2025, 10, 13), 'Mariana Oliveira', 'Fã de séries'),
Aniversario(DateTime(2025, 10, 14), 'Nicolas Barbosa', 'Gosta de arte contemporânea'),
Aniversario(DateTime(2025, 10, 15), 'Olívia Gomes', 'Fã de literatura de suspense'),
Aniversario(DateTime(2025, 10, 16), 'Pedro Farias', 'Curte arte digital'),
Aniversario(DateTime(2025, 10, 17), 'Quitéria Silva', 'Ama esportes ao ar livre'),
Aniversario(DateTime(2025, 10, 18), 'Rafael Costa', 'Fã de fotografia de natureza'),
Aniversario(DateTime(2025, 10, 19), 'Sofia Tavares', 'Ama costura'),
Aniversario(DateTime(2025, 10, 20), 'Thiago Almeida', 'Gosta de esportes radicais'),
Aniversario(DateTime(2025, 10, 21), 'Úrsula Souza', 'Fã de ciclismo'),
Aniversario(DateTime(2025, 10, 22), 'Vítor Lima', 'Ama esportes de inverno'),
Aniversario(DateTime(2025, 10, 23), 'Wanda Costa', 'Fã de literatura histórica'),
Aniversario(DateTime(2025, 10, 24), 'Xande Martins', 'Ama filmes de terror'),
Aniversario(DateTime(2025, 10, 25), 'Yasmin Almeida', 'Gosta de fazer tricô'),
Aniversario(DateTime(2025, 10, 26), 'Zeca Souza', 'Curte música eletrônica'),
Aniversario(DateTime(2025, 10, 27), 'Aline Lima', 'Fã de cultura japonesa'),
Aniversario(DateTime(2025, 10, 28), 'Brenda Oliveira', 'Ama fazer arte com papel'),
Aniversario(DateTime(2025, 10, 29), 'Caio Rocha', 'Gosta de vinho'),
Aniversario(DateTime(2025, 10, 30), 'Daniela Nunes', 'Fã de jardinagem urbana'),
Aniversario(DateTime(2025, 10, 31), 'Eduardo Ferreira', 'Gosta de filmes de terror'),
Aniversario(DateTime(2025, 11, 1), 'Ana Silva', 'Ama caminhar na natureza'),
Aniversario(DateTime(2025, 11, 2), 'Bruno Costa', 'Curte música indie'),
Aniversario(DateTime(2025, 11, 3), 'Carla Lima', 'Fã de filmes de ação'),
Aniversario(DateTime(2025, 11, 4), 'Davi Oliveira', 'Gosta de futebol'),
Aniversario(DateTime(2025, 11, 5), 'Elena Martins', 'Ama cozinhar'),
Aniversario(DateTime(2025, 11, 6), 'Fábio Tavares', 'Curte ciclismo de estrada'),
Aniversario(DateTime(2025, 11, 7), 'Giovana Farias', 'Fã de teatro'),
Aniversario(DateTime(2025, 11, 8), 'Henrique Souza', 'Curte arte digital'),
Aniversario(DateTime(2025, 11, 9), 'Isadora Rocha', 'Fã de séries de suspense'),
Aniversario(DateTime(2025, 11, 10), 'João Santos', 'Ama videogames'),
Aniversario(DateTime(2025, 11, 11), 'Karla Almeida', 'Fã de arquitetura'),
Aniversario(DateTime(2025, 11, 12), 'Leo Costa', 'Curte caminhar na praia'),
Aniversario(DateTime(2025, 11, 13), 'Mariana Oliveira', 'Fã de culinária internacional'),
Aniversario(DateTime(2025, 11, 14), 'Nicolas Silva', 'Ama filmes clássicos'),
Aniversario(DateTime(2025, 11, 15), 'Olívia Souza', 'Curte praticar yoga'),
Aniversario(DateTime(2025, 11, 16), 'Pedro Farias', 'Ama skate'),
Aniversario(DateTime(2025, 11, 17), 'Quitéria Rocha', 'Fã de arte contemporânea'),
Aniversario(DateTime(2025, 11, 18), 'Rafael Costa', 'Ama filmes de terror'),
Aniversario(DateTime(2025, 11, 19), 'Sofia Lima', 'Gosta de jardinagem'),
Aniversario(DateTime(2025, 11, 20), 'Thiago Oliveira', 'Curte esportes aquáticos'),
Aniversario(DateTime(2025, 11, 21), 'Úrsula Farias', 'Fã de fotografia'),
Aniversario(DateTime(2025, 11, 22), 'Vítor Pereira', 'Curte maratonas de filmes'),
Aniversario(DateTime(2025, 11, 23), 'Wanda Souza', 'Ama fazer tricô'),
Aniversario(DateTime(2025, 11, 24), 'Xande Lima', 'Fã de música eletrônica'),
Aniversario(DateTime(2025, 11, 25), 'Yasmin Costa', 'Ama literatura policial'),
Aniversario(DateTime(2025, 11, 26), 'Zeca Martins', 'Fã de culinária italiana'),
Aniversario(DateTime(2025, 11, 27), 'Aline Rocha', 'Gosta de dançar'),
Aniversario(DateTime(2025, 11, 28), 'Brenda Almeida', 'Fã de colecionismo'),
Aniversario(DateTime(2025, 11, 29), 'Caio Souza', 'Gosta de jardinagem urbana'),
Aniversario(DateTime(2025, 11, 30), 'Daniela Tavares', 'Curte caminhada ao ar livre'),
Aniversario(DateTime(2025, 12, 1), 'Ana Silva', 'Ama caminhadas ao ar livre'),
Aniversario(DateTime(2025, 12, 2), 'Bruno Costa', 'Curte música clássica'),
Aniversario(DateTime(2025, 12, 3), 'Carla Almeida', 'Fã de culinária italiana'),
Aniversario(DateTime(2025, 12, 4), 'Davi Tavares', 'Ama praticar esportes radicais'),
Aniversario(DateTime(2025, 12, 5), 'Elena Lima', 'Fã de filmes de ação'),
Aniversario(DateTime(2025, 12, 6), 'Fábio Silva', 'Gosta de fotografia'),
Aniversario(DateTime(2025, 12, 7), 'Giovana Rocha', 'Ama jardinagem'),
Aniversario(DateTime(2025, 12, 8), 'Henrique Souza', 'Curte música indie'),
Aniversario(DateTime(2025, 12, 9), 'Isadora Nunes', 'Fã de literatura'),
Aniversario(DateTime(2025, 12, 10), 'João Oliveira', 'Gosta de praticar yoga'),
Aniversario(DateTime(2025, 12, 11), 'Karla Tavares', 'Ama costura'),
Aniversario(DateTime(2025, 12, 12), 'Leo Costa', 'Curte história medieval'),
Aniversario(DateTime(2025, 12, 13), 'Mariana Pereira', 'Fã de filmes de terror'),
Aniversario(DateTime(2025, 12, 14), 'Nicolas Lima', 'Gosta de videogames'),
Aniversario(DateTime(2025, 12, 15), 'Olívia Martins', 'Ama fotografia de natureza'),
Aniversario(DateTime(2025, 12, 16), 'Pedro Almeida', 'Fã de esportes ao ar livre'),
Aniversario(DateTime(2025, 12, 17), 'Quitéria Costa', 'Curte culinária vegana'),
Aniversario(DateTime(2025, 12, 18), 'Rafael Oliveira', 'Ama arte contemporânea'),
Aniversario(DateTime(2025, 12, 19), 'Sofia Farias', 'Fã de tricô'),
Aniversario(DateTime(2025, 12, 20), 'Thiago Silva', 'Curte filmes de ficção científica'),
Aniversario(DateTime(2025, 12, 21), 'Úrsula Rocha', 'Fã de astrologia'),
Aniversario(DateTime(2025, 12, 22), 'Vítor Santos', 'Gosta de escrever'),
Aniversario(DateTime(2025, 12, 23), 'Wanda Souza', 'Fã de colecionismo'),
Aniversario(DateTime(2025, 12, 24), 'Xande Lima', 'Gosta de viajar'),
Aniversario(DateTime(2025, 12, 25), 'Yasmin Costa', 'Ama fazer arte com papel'),
Aniversario(DateTime(2025, 12, 26), 'Zeca Pereira', 'Fã de música rock'),
Aniversario(DateTime(2025, 12, 27), 'Aline Lima', 'Gosta de esportes aquáticos'),
Aniversario(DateTime(2025, 12, 28), 'Brenda Farias', 'Ama artesanato'),
Aniversario(DateTime(2025, 12, 29), 'Caio Oliveira', 'Curte fotografia artística'),
Aniversario(DateTime(2025, 12, 30), 'Daniela Costa', 'Ama esportes radicais'),
Aniversario(DateTime(2025, 12, 31), 'Eduardo Nunes', 'Fã de tecnologia'),
  ];
  
  static adicionarAniversario(Aniversario aniversario){
    AniversarioList.lista.add(aniversario);
    }
  static removerAniversario(Aniversario aniversario){
        AniversarioList.lista.removeWhere((niver)=>niver.nomeAniversariante == (aniversario.nomeAniversariante) && niver.detalhes == aniversario.detalhes && aniversario.data == niver.data);
  }
  static List <Aniversario> getProximosAniversarios(){
    List <Aniversario> lista= List.from(
      AniversarioList.lista.where(
        (a)=>(a.data.month.compareTo(DateTime.now().month) == 0 
        && a.data.day.compareTo(DateTime.now().day) >= 0 ) ||a.data.month.compareTo(DateTime.now().month) >0
      )
    );
    lista.sort((a,b)=>a.data.compareTo(b.data));
    return lista;
  }
  static List <Aniversario> filtrarAniversariosPorNome(String nome){
      List <Aniversario> lista = List.from(
    AniversarioList.lista.where(
    (a) =>a.nomeAniversariante.contains(nome))
    );
    return lista;
  }
  static List<Aniversario> filtrarAniversariosPorDataENome(DateTime data,String nome){
    List <Aniversario> lista = List.from(
      AniversarioList.lista.where(
      (a) => a.data.month.compareTo(data.month).isEven && a.data.day.compareTo(data.day).isEven
      )
    );
    lista = List.from(
    lista.where(
    (a) =>a.nomeAniversariante.contains(nome))
    );
    return lista;
  }
  static bool mesmaData(DateTime data1, DateTime data2) {
  return data1.year == data2.year &&
         data1.month == data2.month &&
         data1.day == data2.day;
}
}