import "Aniversario.dart";
import "Usuario.dart";
class AniversarioList {
  static List <Aniversario> lista= [
    Aniversario(DateTime(2025, 4, 1), Usuario(login: 'ana01', senha: 'senha01', nome: 'Ana Silveira'), 'Ama fotografia de paisagens', 'Filtro ND para câmera'),

    Aniversario(DateTime(2025, 4, 1), Usuario(login: 'ana01', senha: 'senha01', nome: 'Ana Biqueira'), 'Ama fotografia de paisagens', 'Filtro ND para câmera'),
    Aniversario(DateTime(2025, 4, 2), Usuario(login: 'bruno02', senha: 'senha02', nome: 'Bruno Teixeira'), 'Fã de documentários', 'Assinatura de streaming de docs'),
    Aniversario(DateTime(2025, 4, 3), Usuario(login: 'carla03', senha: 'senha03', nome: 'Carla Nogueira'), 'Gosta de culinária vegana', 'Livro de receitas veganas'),
    Aniversario(DateTime(2025, 4, 4), Usuario(login: 'diego04', senha: 'senha04', nome: 'Diego Souza'), 'Ama esportes radicais', 'Vale para bungee jump'),
    Aniversario(DateTime(2025, 4, 5), Usuario(login: 'elisa05', senha: 'senha05', nome: 'Elisa Fernandes'), 'Curte plantas raras', 'Muda de planta exótica'),
    Aniversario(DateTime(2025, 4, 6), Usuario(login: 'fabio06', senha: 'senha06', nome: 'Fábio Torres'), 'Fã de astronomia', 'Livro “Cosmos”'),
    Aniversario(DateTime(2025, 4, 7), Usuario(login: 'gabriela07', senha: 'senha07', nome: 'Gabriela Mello'), 'Ama escultura', 'Kit de argila para modelagem'),
    Aniversario(DateTime(2025, 4, 8), Usuario(login: 'henrique08', senha: 'senha08', nome: 'Henrique Diniz'), 'Fã de jogos indie', 'Gift card da Steam'),
    Aniversario(DateTime(2025, 4, 9), Usuario(login: 'isabel09', senha: 'senha09', nome: 'Isabel Correia'), 'Gosta de meditação', 'Almofada de zafu'),
    Aniversario(DateTime(2025, 4, 10), Usuario(login: 'joao10', senha: 'senha10', nome: 'João Barros'), 'Ama cozinhar churrasco', 'Conjunto de espetos'),
    Aniversario(DateTime(2025, 4, 11), Usuario(login: 'karla11', senha: 'senha11', nome: 'Karla Fontes'), 'Curte moda sustentável', 'Bolsa ecológica artesanal'),
    Aniversario(DateTime(2025, 4, 12), Usuario(login: 'leo12', senha: 'senha12', nome: 'Leonardo Mendes'), 'Fã de kart', 'Volante de simulação'),
    Aniversario(DateTime(2025, 4, 13), Usuario(login: 'marina13', senha: 'senha13', nome: 'Marina Cardoso'), 'Gosta de costura', 'Tesoura profissional'),
    Aniversario(DateTime(2025, 4, 14), Usuario(login: 'nicolas14', senha: 'senha14', nome: 'Nicolas Brito'), 'Fã de jazz', 'CD raro de Miles Davis'),
    Aniversario(DateTime(2025, 4, 15), Usuario(login: 'olivia15', senha: 'senha15', nome: 'Olívia Sales'), 'Ama arquitetura', 'Luminária moderna de design'),
    Aniversario(DateTime(2025, 4, 16), Usuario(login: 'pedro16', senha: 'senha16', nome: 'Pedro Leal'), 'Fã de drones', 'Mini drone portátil'),
    Aniversario(DateTime(2025, 4, 17), Usuario(login: 'quiteria17', senha: 'senha17', nome: 'Quitéria Lopes'), 'Gosta de dança clássica', 'DVD de balé russo'),
    Aniversario(DateTime(2025, 4, 18), Usuario(login: 'renan18', senha: 'senha18', nome: 'Renan Lima'), 'Curte astronomia', 'Mapa celeste detalhado'),
    Aniversario(DateTime(2025, 4, 19), Usuario(login: 'sabrina19', senha: 'senha19', nome: 'Sabrina Pires'), 'Ama papelaria', 'Planner com adesivos'),
    Aniversario(DateTime(2025, 4, 20), Usuario(login: 'thiago20', senha: 'senha20', nome: 'Thiago Amaral'), 'Fã de esportes', 'Camiseta personalizada do time'),
    Aniversario(DateTime(2025, 4, 21), Usuario(login: 'ursula21', senha: 'senha21', nome: 'Úrsula Soares'), 'Curte música clássica', 'Ingresso para concerto'),
    Aniversario(DateTime(2025, 4, 22), Usuario(login: 'vagner22', senha: 'senha22', nome: 'Vagner Bezerra'), 'Ama pets', 'Coleira com nome gravado'),
    Aniversario(DateTime(2025, 4, 23), Usuario(login: 'wanda23', senha: 'senha23', nome: 'Wanda Teles'), 'Gosta de gastronomia', 'Curso online de culinária italiana'),
    Aniversario(DateTime(2025, 4, 24), Usuario(login: 'xisto24', senha: 'senha24', nome: 'Xisto Azevedo'), 'Fã de tecnologia retrô', 'Game Boy de coleção'),
    Aniversario(DateTime(2025, 4, 25), Usuario(login: 'yara25', senha: 'senha25', nome: 'Yara Campos'), 'Curte samba', 'CD clássico de Cartola'),
    Aniversario(DateTime(2025, 4, 26), Usuario(login: 'zacarias26', senha: 'senha26', nome: 'Zacarias Rocha'), 'Ama vinhos', 'Taças de cristal'),
    Aniversario(DateTime(2025, 4, 27), Usuario(login: 'aline27', senha: 'senha27', nome: 'Aline Figueiredo'), 'Fã de literatura russa', 'Box Dostoiévski'),
    Aniversario(DateTime(2025, 4, 28), Usuario(login: 'breno28', senha: 'senha28', nome: 'Breno Assunção'), 'Gosta de alpinismo', 'Mosquetão profissional'),
    Aniversario(DateTime(2025, 4, 29), Usuario(login: 'camila29', senha: 'senha29', nome: 'Camila Xavier'), 'Fã de tecnologia', 'Smartwatch básico'),
    Aniversario(DateTime(2025, 4, 30), Usuario(login: 'daniel30', senha: 'senha30', nome: 'Daniel Guimarães'), 'Curte mixologia', 'Kit de coquetelaria'),
    Aniversario(DateTime(2025, 3, 1), Usuario(login: 'arthur01', senha: 'senha01', nome: 'Arthur Ramos'), 'Gosta de pesca', 'Conjunto de iscas'),
    Aniversario(DateTime(2025, 3, 2), Usuario(login: 'bia02', senha: 'senha02', nome: 'Bia Albuquerque'), 'Ama culinária francesa', 'Queijo importado'),
    Aniversario(DateTime(2025, 3, 3), Usuario(login: 'carlos03', senha: 'senha03', nome: 'Carlos Sampaio'), 'Fã de trilhas', 'Garrafa térmica'),
    Aniversario(DateTime(2025, 3, 4), Usuario(login: 'duda04', senha: 'senha04', nome: 'Duda Vasconcelos'), 'Gosta de astrologia', 'Cristais energéticos'),
    Aniversario(DateTime(2025, 3, 5), Usuario(login: 'edu05', senha: 'senha05', nome: 'Eduardo Pinheiro'), 'Ama jardinagem', 'Regador personalizado'),
    Aniversario(DateTime(2025, 3, 6), Usuario(login: 'fernanda06', senha: 'senha06', nome: 'Fernanda Melo'), 'Curte esportes aquáticos', 'Prancha de bodyboard'),
    Aniversario(DateTime(2025, 3, 7), Usuario(login: 'gustavo07', senha: 'senha07', nome: 'Gustavo Reis'), 'Fã de ficção científica', 'Box de Star Wars'),
    Aniversario(DateTime(2025, 3, 8), Usuario(login: 'helena08', senha: 'senha08', nome: 'Helena Dias'), 'Gosta de pintura', 'Curso online de aquarela'),
    Aniversario(DateTime(2025, 3, 9), Usuario(login: 'igor09', senha: 'senha09', nome: 'Igor Farias'), 'Ama cinema europeu', 'Assinatura de streaming'),
    Aniversario(DateTime(2025, 3, 10), Usuario(login: 'juliana10', senha: 'senha10', nome: 'Juliana Torres'), 'Coleciona moedas', 'Moeda rara de prata'),
    Aniversario(DateTime(2025, 3, 11), Usuario(login: 'kevin11', senha: 'senha11', nome: 'Kevin Rocha'), 'Fã de culinária mexicana', 'Kit de tacos'),
    Aniversario(DateTime(2025, 3, 12), Usuario(login: 'lara12', senha: 'senha12', nome: 'Lara Matos'), 'Gosta de astronomia', 'Mini telescópio'),
    Aniversario(DateTime(2025, 3, 13), Usuario(login: 'mateus13', senha: 'senha13', nome: 'Mateus Braga'), 'Curte marcenaria', 'Kit de ferramentas'),
    Aniversario(DateTime(2025, 3, 14), Usuario(login: 'nina14', senha: 'senha14', nome: 'Nina Cunha'), 'Ama bordado', 'Kit de bordado criativo'),
    Aniversario(DateTime(2025, 3, 15), Usuario(login: 'oscar15', senha: 'senha15', nome: 'Oscar Peixoto'), 'Gosta de patinação', 'Protetores de joelho'),
    Aniversario(DateTime(2025, 3, 16), Usuario(login: 'patricia16', senha: 'senha16', nome: 'Patrícia Gomes'), 'Fã de moda vintage', 'Lenço retrô'),
    Aniversario(DateTime(2025, 3, 17), Usuario(login: 'rafael17', senha: 'senha17', nome: 'Rafael Monteiro'), 'Ama violão', 'Palhetas personalizadas'),
    Aniversario(DateTime(2025, 3, 18), Usuario(login: 'sara18', senha: 'senha18', nome: 'Sara Martins'), 'Gosta de yoga', 'Roupas confortáveis'),
    Aniversario(DateTime(2025, 3, 19), Usuario(login: 'tiago19', senha: 'senha19', nome: 'Tiago Duarte'), 'Fã de séries', 'Camiseta de Stranger Things'),
    Aniversario(DateTime(2025, 3, 20), Usuario(login: 'ursula20', senha: 'senha20', nome: 'Úrsula Lima'), 'Ama natureza', 'Vaso autoirrigável'),
    Aniversario(DateTime(2025, 3, 21), Usuario(login: 'victor21', senha: 'senha21', nome: 'Victor Oliveira'), 'Fã de basquete', 'Camisa da NBA'),
    Aniversario(DateTime(2025, 3, 22), Usuario(login: 'wendy22', senha: 'senha22', nome: 'Wendy Pacheco'), 'Gosta de danças latinas', 'Curso de salsa online'),
    Aniversario(DateTime(2025, 3, 23), Usuario(login: 'xander23', senha: 'senha23', nome: 'Xander Campos'), 'Ama trilhas', 'Kit de sobrevivência'),
    Aniversario(DateTime(2025, 3, 24), Usuario(login: 'yasmin24', senha: 'senha24', nome: 'Yasmin Barros'), 'Fã de design gráfico', 'Mesa digitalizadora'),
    Aniversario(DateTime(2025, 3, 25), Usuario(login: 'zara25', senha: 'senha25', nome: 'Zara Rodrigues'), 'Curte aromaterapia', 'Difusor de essências'),
    Aniversario(DateTime(2025, 3, 26), Usuario(login: 'abel26', senha: 'senha26', nome: 'Abel Furtado'), 'Ama fotografia', 'Mini tripé de celular'),
    Aniversario(DateTime(2025, 3, 27), Usuario(login: 'beatriz27', senha: 'senha27', nome: 'Beatriz Alves'), 'Gosta de leitura clássica', 'Box de Jane Austen'),
    Aniversario(DateTime(2025, 3, 28), Usuario(login: 'caio28', senha: 'senha28', nome: 'Caio Moreira'), 'Fã de rock', 'Vinil do Queen'),
    Aniversario(DateTime(2025, 3, 29), Usuario(login: 'daniela29', senha: 'senha29', nome: 'Daniela Rocha'), 'Ama origami', 'Papel japonês'),
    Aniversario(DateTime(2025, 3, 30), Usuario(login: 'eduarda30', senha: 'senha30', nome: 'Eduarda Nunes'), 'Curte aventuras', 'Mapa de trilhas'),
    Aniversario(DateTime(2025, 3, 31), Usuario(login: 'fabio31', senha: 'senha31', nome: 'Fábio Mendes'), 'Fã de futebol', 'Chaveiro do time do coração'),
    Aniversario(DateTime(2025, 2, 1), Usuario(login: 'ana01', senha: 'senha01', nome: 'Ana Paula'), 'Ama flores e poesia', 'Buquê de rosas'),
    Aniversario(DateTime(2025, 2, 2), Usuario(login: 'bruno02', senha: 'senha02', nome: 'Bruno Lima'), 'Fã de esportes radicais', 'Skate'),
    Aniversario(DateTime(2025, 2, 3), Usuario(login: 'carla03', senha: 'senha03', nome: 'Carla Souza'), 'Gosta de cozinhar', 'Kit de culinária'),
    Aniversario(DateTime(2025, 2, 4), Usuario(login: 'diego04', senha: 'senha04', nome: 'Diego Torres'), 'Apreciador de vinho', 'Garrafa de vinho'),
    Aniversario(DateTime(2025, 2, 5), Usuario(login: 'elisa05', senha: 'senha05', nome: 'Elisa Martins'), 'Ama gatos', 'Camiseta de gato'),
    Aniversario(DateTime(2025, 2, 6), Usuario(login: 'fabio06', senha: 'senha06', nome: 'Fábio Rocha'), 'Coleciona action figures', 'Boneco do Batman'),
    Aniversario(DateTime(2025, 2, 7), Usuario(login: 'gabi07', senha: 'senha07', nome: 'Gabriela Dias'), 'Ama fotografia', 'Câmera instantânea'),
    Aniversario(DateTime(2025, 2, 8), Usuario(login: 'henrique08', senha: 'senha08', nome: 'Henrique Alves'), 'Curte videogames', 'Controle de Xbox'),
    Aniversario(DateTime(2025, 2, 9), Usuario(login: 'isabela09', senha: 'senha09', nome: 'Isabela Pires'), 'Fã de música clássica', 'CD de Beethoven'),
    Aniversario(DateTime(2025, 2, 10), Usuario(login: 'joao10', senha: 'senha10', nome: 'João Pedro'), 'Ama futebol', 'Camisa do time favorito'),
    Aniversario(DateTime(2025, 2, 11), Usuario(login: 'karla11', senha: 'senha11', nome: 'Karla Monteiro'), 'Curte astrologia', 'Mapa astral personalizado'),
    Aniversario(DateTime(2025, 2, 12), Usuario(login: 'leonardo12', senha: 'senha12', nome: 'Leonardo Vieira'), 'Ama livros de ficção', 'Box de Harry Potter'),
    Aniversario(DateTime(2025, 2, 13), Usuario(login: 'marina13', senha: 'senha13', nome: 'Marina Freitas'), 'Gosta de plantas', 'Vaso de suculenta'),
    Aniversario(DateTime(2025, 2, 14), Usuario(login: 'nicolas14', senha: 'senha14', nome: 'Nicolas Duarte'), 'Fã de animes', 'Camisa de Naruto'),
    Aniversario(DateTime(2025, 2, 15), Usuario(login: 'olivia15', senha: 'senha15', nome: 'Olívia Ramos'), 'Ama yoga', 'Tapete de yoga'),
    Aniversario(DateTime(2025, 2, 16), Usuario(login: 'paulo16', senha: 'senha16', nome: 'Paulo César'), 'Gosta de astronomia', 'Telescópio pequeno'),
    Aniversario(DateTime(2025, 2, 17), Usuario(login: 'quiteria17', senha: 'senha17', nome: 'Quitéria Lopes'), 'Curte arte moderna', 'Quadro abstrato'),
    Aniversario(DateTime(2025, 2, 18), Usuario(login: 'rafael18', senha: 'senha18', nome: 'Rafael Nogueira'), 'Gosta de trilhas', 'Mochila de camping'),
    Aniversario(DateTime(2025, 2, 19), Usuario(login: 'sabrina19', senha: 'senha19', nome: 'Sabrina Teixeira'), 'Ama maquiagem', 'Kit de maquiagem'),
    Aniversario(DateTime(2025, 2, 20), Usuario(login: 'tiago20', senha: 'senha20', nome: 'Tiago Fonseca'), 'Fã de tecnologia', 'Smartwatch'),
    Aniversario(DateTime(2025, 2, 21), Usuario(login: 'ursula21', senha: 'senha21', nome: 'Úrsula Silva'), 'Ama natureza', 'Livro sobre ecologia'),
    Aniversario(DateTime(2025, 2, 22), Usuario(login: 'victor22', senha: 'senha22', nome: 'Victor Hugo'), 'Coleciona moedas', 'Kit de moedas antigas'),
    Aniversario(DateTime(2025, 2, 23), Usuario(login: 'wanda23', senha: 'senha23', nome: 'Wanda Santos'), 'Gosta de artesanato', 'Kit de pintura'),
    Aniversario(DateTime(2025, 2, 24), Usuario(login: 'xavier24', senha: 'senha24', nome: 'Xavier Campos'), 'Fã de ficção científica', 'Livro de Asimov'),
    Aniversario(DateTime(2025, 2, 25), Usuario(login: 'yasmin25', senha: 'senha25', nome: 'Yasmin Oliveira'), 'Ama dança', 'Tênis de dança'),
    Aniversario(DateTime(2025, 2, 26), Usuario(login: 'zeca26', senha: 'senha26', nome: 'Zeca Barreto'), 'Gosta de café', 'Cafeteira portátil'),
    Aniversario(DateTime(2025, 2, 27), Usuario(login: 'aline27', senha: 'senha27', nome: 'Aline Costa'), 'Ama cinema', 'Coleção de DVDs clássicos'),
    Aniversario(DateTime(2025, 2, 28), Usuario(login: 'bernardo28', senha: 'senha28', nome: 'Bernardo Luz'), 'Curte culinária japonesa', 'Kit sushi caseiro'),
    Aniversario(DateTime(2025, 1, 1), Usuario(login: 'alice01', senha: 'senha01', nome: 'Alice Carvalho'), 'Gosta de caminhar na praia', 'Chapéu de sol'),
    Aniversario(DateTime(2025, 1, 2), Usuario(login: 'beto02', senha: 'senha02', nome: 'Beto Andrade'), 'Ama carros antigos', 'Miniatura de Mustang'),
    Aniversario(DateTime(2025, 1, 3), Usuario(login: 'clara03', senha: 'senha03', nome: 'Clara Lima'), 'Fã de filmes de ação', 'Blu-ray de Velozes e Furiosos'),
    Aniversario(DateTime(2025, 1, 4), Usuario(login: 'daniel04', senha: 'senha04', nome: 'Daniel Moura'), 'Coleciona selos', 'Álbum de selos'),
    Aniversario(DateTime(2025, 1, 5), Usuario(login: 'erika05', senha: 'senha05', nome: 'Erika Tavares'), 'Ama patinação', 'Patins novos'),
    Aniversario(DateTime(2025, 1, 6), Usuario(login: 'felipe06', senha: 'senha06', nome: 'Felipe Sanches'), 'Toca violão', 'Afinador eletrônico'),
    Aniversario(DateTime(2025, 1, 7), Usuario(login: 'giovana07', senha: 'senha07', nome: 'Giovana Castro'), 'Fã de café', 'Kit de café gourmet'),
    Aniversario(DateTime(2025, 1, 8), Usuario(login: 'heitor08', senha: 'senha08', nome: 'Heitor Souza'), 'Curte mergulho', 'Óculos de mergulho'),
    Aniversario(DateTime(2025, 1, 9), Usuario(login: 'ivana09', senha: 'senha09', nome: 'Ivana Rocha'), 'Gosta de moda', 'Lenço de seda'),
    Aniversario(DateTime(2025, 1, 10), Usuario(login: 'joel10', senha: 'senha10', nome: 'Joel Mendes'), 'Ama ciclismo', 'Luz traseira para bike'),
    Aniversario(DateTime(2025, 1, 11), Usuario(login: 'karine11', senha: 'senha11', nome: 'Karine Luz'), 'Fã de arte japonesa', 'Estampa ukiyo-e'),
    Aniversario(DateTime(2025, 1, 12), Usuario(login: 'lucas12', senha: 'senha12', nome: 'Lucas Freitas'), 'Curte trilhas', 'Tênis de caminhada'),
    Aniversario(DateTime(2025, 1, 13), Usuario(login: 'marcela13', senha: 'senha13', nome: 'Marcela Guedes'), 'Ama astronomia', 'Poster das fases da lua'),
    Aniversario(DateTime(2025, 1, 14), Usuario(login: 'nilo14', senha: 'senha14', nome: 'Nilo Prado'), 'Gosta de mágica', 'Baralho de truques'),
    Aniversario(DateTime(2025, 1, 15), Usuario(login: 'olga15', senha: 'senha15', nome: 'Olga Martins'), 'Curte natação', 'Touca personalizada'),
    Aniversario(DateTime(2025, 1, 16), Usuario(login: 'paulo16', senha: 'senha16', nome: 'Paulo Viana'), 'Ama pintura', 'Kit de aquarela'),
    Aniversario(DateTime(2025, 1, 17), Usuario(login: 'quenia17', senha: 'senha17', nome: 'Quênia Silveira'), 'Fã de podcasts', 'Fone de ouvido Bluetooth'),
    Aniversario(DateTime(2025, 1, 18), Usuario(login: 'rafaela18', senha: 'senha18', nome: 'Rafaela Mourão'), 'Gosta de jardinagem', 'Kit de ferramentas para plantas'),
    Aniversario(DateTime(2025, 1, 19), Usuario(login: 'samuel19', senha: 'senha19', nome: 'Samuel Reis'), 'Ama basquete', 'Bola oficial'),
    Aniversario(DateTime(2025, 1, 20), Usuario(login: 'tania20', senha: 'senha20', nome: 'Tânia Meireles'), 'Fã de cinema antigo', 'DVDs clássicos'),
    Aniversario(DateTime(2025, 1, 21), Usuario(login: 'ulysses21', senha: 'senha21', nome: 'Ulysses Lopes'), 'Gosta de vinil', 'Disco raro de jazz'),
    Aniversario(DateTime(2025, 1, 22), Usuario(login: 'valeria22', senha: 'senha22', nome: 'Valéria Gomes'), 'Ama esportes aquáticos', 'Colete salva-vidas'),
    Aniversario(DateTime(2025, 1, 23), Usuario(login: 'willian23', senha: 'senha23', nome: 'Willian Costa'), 'Gosta de tecnologia', 'Hub USB-C'),
    Aniversario(DateTime(2025, 1, 24), Usuario(login: 'xuxa24', senha: 'senha24', nome: 'Xuxa Ferreira'), 'Fã de dança', 'Meia antiderrapante'),
    Aniversario(DateTime(2025, 1, 25), Usuario(login: 'yasmin25', senha: 'senha25', nome: 'Yasmin Duarte'), 'Curte teatro', 'Ingressos para peça'),
    Aniversario(DateTime(2025, 1, 26), Usuario(login: 'zico26', senha: 'senha26', nome: 'Zico Amaral'), 'Ama carros de corrida', 'Boné da F1'),
    Aniversario(DateTime(2025, 1, 27), Usuario(login: 'aline27', senha: 'senha27', nome: 'Aline Matos'), 'Fã de culinária italiana', 'Livro de receitas'),
    Aniversario(DateTime(2025, 1, 28), Usuario(login: 'bernardo28', senha: 'senha28', nome: 'Bernardo Nery'), 'Gosta de história', 'Livro sobre Império Romano'),
    Aniversario(DateTime(2025, 1, 29), Usuario(login: 'carol29', senha: 'senha29', nome: 'Carol Ribeiro'), 'Ama jogos de tabuleiro', 'Jogo Dixit'),
    Aniversario(DateTime(2025, 1, 30), Usuario(login: 'douglas30', senha: 'senha30', nome: 'Douglas Rocha'), 'Fã de cervejas artesanais', 'Kit de copos especiais'),
    Aniversario(DateTime(2025, 1, 31), Usuario(login: 'emilia31', senha: 'senha31', nome: 'Emília Barreto'), 'Ama astronomia', 'Mapa estelar do dia do nascimento'),
    Aniversario(DateTime(2025, 5, 1), Usuario(login: 'aline01', senha: 'senha01', nome: 'Aline Barbosa'), 'Ama fotografia urbana', 'Curso de fotografia de rua'),
  Aniversario(DateTime(2025, 5, 2), Usuario(login: 'bernardo02', senha: 'senha02', nome: 'Bernardo Torres'), 'Fã de RPG', 'Livro de D&D'),
  Aniversario(DateTime(2025, 5, 3), Usuario(login: 'caroline03', senha: 'senha03', nome: 'Caroline Farias'), 'Curte plantas suculentas', 'Kit de mini vasos'),
  Aniversario(DateTime(2025, 5, 4), Usuario(login: 'diego04', senha: 'senha04', nome: 'Diego Nascimento'), 'Ama ciclismo', 'Luz traseira de bicicleta'),
  Aniversario(DateTime(2025, 5, 5), Usuario(login: 'elena05', senha: 'senha05', nome: 'Elena Braga'), 'Fã de mitologia', 'Livro ilustrado de mitologia grega'),
  Aniversario(DateTime(2025, 5, 6), Usuario(login: 'fabiana06', senha: 'senha06', nome: 'Fabiana Cunha'), 'Gosta de chá', 'Caixa de chás artesanais'),
  Aniversario(DateTime(2025, 5, 7), Usuario(login: 'gustavo07', senha: 'senha07', nome: 'Gustavo Ramos'), 'Curte caminhadas', 'Boné esportivo'),
  Aniversario(DateTime(2025, 5, 8), Usuario(login: 'helena08', senha: 'senha08', nome: 'Helena Duarte'), 'Ama costura criativa', 'Tecidos estampados'),
  Aniversario(DateTime(2025, 5, 9), Usuario(login: 'ian09', senha: 'senha09', nome: 'Ian Peixoto'), 'Fã de tênis', 'Raquete nova'),
  Aniversario(DateTime(2025, 5, 10), Usuario(login: 'jessica10', senha: 'senha10', nome: 'Jéssica Oliveira'), 'Curte astrologia', 'Mapa astral personalizado'),
  Aniversario(DateTime(2025, 5, 11), Usuario(login: 'kaique11', senha: 'senha11', nome: 'Kaique Martins'), 'Gosta de escrita', 'Caderno de couro'),
  Aniversario(DateTime(2025, 5, 12), Usuario(login: 'laura12', senha: 'senha12', nome: 'Laura Ferreira'), 'Ama cinema nacional', 'DVDs clássicos BR'),
  Aniversario(DateTime(2025, 5, 13), Usuario(login: 'matheus13', senha: 'senha13', nome: 'Matheus Reis'), 'Fã de robótica', 'Kit Arduino'),
  Aniversario(DateTime(2025, 5, 14), Usuario(login: 'natalia14', senha: 'senha14', nome: 'Natália Souza'), 'Gosta de praia', 'Canga personalizada'),
  Aniversario(DateTime(2025, 5, 15), Usuario(login: 'otavio15', senha: 'senha15', nome: 'Otávio Araújo'), 'Ama fotografia analógica', 'Câmera descartável'),
  Aniversario(DateTime(2025, 5, 16), Usuario(login: 'paula16', senha: 'senha16', nome: 'Paula Antunes'), 'Fã de decoração', 'Luminária criativa'),
  Aniversario(DateTime(2025, 5, 17), Usuario(login: 'rafael17', senha: 'senha17', nome: 'Rafael Tavares'), 'Curte trilhas', 'Tênis de caminhada'),
  Aniversario(DateTime(2025, 5, 18), Usuario(login: 'sandra18', senha: 'senha18', nome: 'Sandra Dias'), 'Ama doces caseiros', 'Kit de confeitaria'),
  Aniversario(DateTime(2025, 5, 19), Usuario(login: 'tulio19', senha: 'senha19', nome: 'Túlio Rocha'), 'Fã de skate', 'Chave multiuso para skate'),
  Aniversario(DateTime(2025, 5, 20), Usuario(login: 'ursula20', senha: 'senha20', nome: 'Úrsula Mendes'), 'Gosta de yoga', 'Tapete antideslizante'),
  Aniversario(DateTime(2025, 5, 21), Usuario(login: 'vitor21', senha: 'senha21', nome: 'Vítor Almeida'), 'Ama puzzles', 'Quebra-cabeça de 2000 peças'),
  Aniversario(DateTime(2025, 5, 22), Usuario(login: 'wanda22', senha: 'senha22', nome: 'Wanda Pinto'), 'Fã de vinil', 'LP clássico dos anos 70'),
  Aniversario(DateTime(2025, 5, 23), Usuario(login: 'xavier23', senha: 'senha23', nome: 'Xavier Gomes'), 'Gosta de drones', 'Acessório de hélice'),
  Aniversario(DateTime(2025, 5, 24), Usuario(login: 'yasmin24', senha: 'senha24', nome: 'Yasmin Ribeiro'), 'Ama dança urbana', 'Tênis para dança'),
  Aniversario(DateTime(2025, 5, 25), Usuario(login: 'zuleika25', senha: 'senha25', nome: 'Zuleika Costa'), 'Curte fotografia noturna', 'Lanterna de LED para câmera'),
  Aniversario(DateTime(2025, 5, 26), Usuario(login: 'alberto26', senha: 'senha26', nome: 'Alberto Lima'), 'Fã de cinema noir', 'Box de filmes clássicos'),
  Aniversario(DateTime(2025, 5, 27), Usuario(login: 'bianca27', senha: 'senha27', nome: 'Bianca Vasconcelos'), 'Gosta de astronomia', 'Planisfério celeste'),
  Aniversario(DateTime(2025, 5, 28), Usuario(login: 'caio28', senha: 'senha28', nome: 'Caio Medeiros'), 'Curte grafite', 'Canetas marcadoras'),
  Aniversario(DateTime(2025, 5, 29), Usuario(login: 'daniela29', senha: 'senha29', nome: 'Daniela Loureiro'), 'Fã de maquiagem artística', 'Kit de pintura facial'),
  Aniversario(DateTime(2025, 5, 30), Usuario(login: 'edson30', senha: 'senha30', nome: 'Edson Carvalho'), 'Gosta de astronomia', 'Aplicativo premium de observação'),
  Aniversario(DateTime(2025, 5, 31), Usuario(login: 'fernanda31', senha: 'senha31', nome: 'Fernanda Rangel'), 'Ama aprender línguas', 'Assinatura de app de idiomas'),
  Aniversario(DateTime(2025, 6, 1), Usuario(login: 'ana01', senha: 'senha01', nome: 'Ana Morais'), 'Gosta de jardinagem', 'Kit de ferramentas para plantas'),
  Aniversario(DateTime(2025, 6, 2), Usuario(login: 'bruno02', senha: 'senha02', nome: 'Bruno Prado'), 'Curte escalada', 'Pó de magnésio para escalada'),
  Aniversario(DateTime(2025, 6, 3), Usuario(login: 'carla03', senha: 'senha03', nome: 'Carla Ribeiro'), 'Ama literatura de suspense', 'Livro de Agatha Christie'),
  Aniversario(DateTime(2025, 6, 4), Usuario(login: 'daniel04', senha: 'senha04', nome: 'Daniel Simões'), 'Fã de esportes aquáticos', 'Óculos de natação profissional'),
  Aniversario(DateTime(2025, 6, 5), Usuario(login: 'elisa05', senha: 'senha05', nome: 'Elisa Goulart'), 'Curte crochê', 'Kit de agulhas e fios'),
  Aniversario(DateTime(2025, 6, 6), Usuario(login: 'fabio06', senha: 'senha06', nome: 'Fábio Andrade'), 'Gosta de programação', 'Livro “Clean Code”'),
  Aniversario(DateTime(2025, 6, 7), Usuario(login: 'giovana07', senha: 'senha07', nome: 'Giovana Lira'), 'Ama dança contemporânea', 'Aula experimental em estúdio'),
  Aniversario(DateTime(2025, 6, 8), Usuario(login: 'heitor08', senha: 'senha08', nome: 'Heitor Castro'), 'Fã de astronomia', 'Telescópio básico'),
  Aniversario(DateTime(2025, 6, 9), Usuario(login: 'isabela09', senha: 'senha09', nome: 'Isabela Dias'), 'Curte moda vintage', 'Lenço retrô anos 60'),
  Aniversario(DateTime(2025, 6, 10), Usuario(login: 'joao10', senha: 'senha10', nome: 'João Batista'), 'Gosta de tocar violão', 'Afinador digital'),
  Aniversario(DateTime(2025, 6, 11), Usuario(login: 'karine11', senha: 'senha11', nome: 'Karine Novaes'), 'Fã de arte digital', 'Mesa digitalizadora básica'),
  Aniversario(DateTime(2025, 6, 12), Usuario(login: 'lucas12', senha: 'senha12', nome: 'Lucas Moraes'), 'Ama futebol', 'Bola oficial da temporada'),
  Aniversario(DateTime(2025, 6, 13), Usuario(login: 'marina13', senha: 'senha13', nome: 'Marina Rocha'), 'Gosta de cozinhar doces', 'Formas de silicone'),
  Aniversario(DateTime(2025, 6, 14), Usuario(login: 'nicolas14', senha: 'senha14', nome: 'Nicolas Figueira'), 'Curte skate', 'Lixa personalizada'),
  Aniversario(DateTime(2025, 6, 15), Usuario(login: 'olga15', senha: 'senha15', nome: 'Olga Mendonça'), 'Ama literatura romântica', 'Box Jane Austen'),
  Aniversario(DateTime(2025, 6, 16), Usuario(login: 'paulo16', senha: 'senha16', nome: 'Paulo Rezende'), 'Fã de cervejas artesanais', 'Kit de degustação'),
  Aniversario(DateTime(2025, 6, 17), Usuario(login: 'quiteria17', senha: 'senha17', nome: 'Quitéria Vieira'), 'Gosta de pintura a óleo', 'Tinta e pincéis profissionais'),
  Aniversario(DateTime(2025, 6, 18), Usuario(login: 'rafaela18', senha: 'senha18', nome: 'Rafaela Neves'), 'Curte costura criativa', 'Alfineteiro magnético'),
  Aniversario(DateTime(2025, 6, 19), Usuario(login: 'samuel19', senha: 'senha19', nome: 'Samuel Oliveira'), 'Fã de tecnologia', 'Hub USB multifuncional'),
  Aniversario(DateTime(2025, 6, 20), Usuario(login: 'tatiane20', senha: 'senha20', nome: 'Tatiane Martins'), 'Ama pets', 'Comedouro inteligente'),
  Aniversario(DateTime(2025, 6, 21), Usuario(login: 'ulysses21', senha: 'senha21', nome: 'Ulysses Barbosa'), 'Gosta de ciclismo', 'Suporte de garrafa para bike'),
  Aniversario(DateTime(2025, 6, 22), Usuario(login: 'valeria22', senha: 'senha22', nome: 'Valéria Duarte'), 'Curte decoração japonesa', 'Quadro de cerejeira'),
  Aniversario(DateTime(2025, 6, 23), Usuario(login: 'wesley23', senha: 'senha23', nome: 'Wesley Pires'), 'Fã de esportes de inverno', 'Gorro térmico'),
  Aniversario(DateTime(2025, 6, 24), Usuario(login: 'xuxa24', senha: 'senha24', nome: 'Xuxa Nascimento'), 'Ama danças folclóricas', 'Vestido de quadrilha'),
  Aniversario(DateTime(2025, 6, 25), Usuario(login: 'yasmin25', senha: 'senha25', nome: 'Yasmin Torres'), 'Curte música eletrônica', 'Fones com isolamento'),
  Aniversario(DateTime(2025, 6, 26), Usuario(login: 'zeca26', senha: 'senha26', nome: 'Zeca Rocha'), 'Gosta de culinária japonesa', 'Kit para sushi'),
  Aniversario(DateTime(2025, 6, 27), Usuario(login: 'aline27', senha: 'senha27', nome: 'Aline Couto'), 'Fã de jazz', 'CD de Ella Fitzgerald'),
  Aniversario(DateTime(2025, 6, 28), Usuario(login: 'brenda28', senha: 'senha28', nome: 'Brenda Castro'), 'Ama yoga', 'Bloco de equilíbrio'),
  Aniversario(DateTime(2025, 6, 29), Usuario(login: 'caio29', senha: 'senha29', nome: 'Caio Nunes'), 'Fã de tecnologia retrô', 'Controle de Atari'),
  Aniversario(DateTime(2025, 6, 30), Usuario(login: 'daniela30', senha: 'senha30', nome: 'Daniela Lemos'), 'Curte moda indie', 'Óculos vintage'),
  Aniversario(DateTime(2025, 7, 1), Usuario(login: 'alice01', senha: 'senha01', nome: 'Alice Martins'), 'Gosta de escrever poesia', 'Caderno artesanal'),
  Aniversario(DateTime(2025, 7, 2), Usuario(login: 'bruno02', senha: 'senha02', nome: 'Bruno Azevedo'), 'Curte trilhas sonoras de filmes', 'Vinil de Hans Zimmer'),
  Aniversario(DateTime(2025, 7, 3), Usuario(login: 'carla03', senha: 'senha03', nome: 'Carla Torres'), 'Ama pintar aquarelas', 'Bloco de papel aquarela'),
  Aniversario(DateTime(2025, 7, 4), Usuario(login: 'davi04', senha: 'senha04', nome: 'Davi Lopes'), 'Fã de jogos de tabuleiro', 'Expansão de Catan'),
  Aniversario(DateTime(2025, 7, 5), Usuario(login: 'elena05', senha: 'senha05', nome: 'Elena Cunha'), 'Gosta de gatos', 'Brinquedo interativo para felinos'),
  Aniversario(DateTime(2025, 7, 6), Usuario(login: 'fabio06', senha: 'senha06', nome: 'Fábio Tavares'), 'Ama snowboard', 'Protetor térmico de pescoço'),
  Aniversario(DateTime(2025, 7, 7), Usuario(login: 'giovana07', senha: 'senha07', nome: 'Giovana Mendes'), 'Fã de origami', 'Kit de papéis decorados'),
  Aniversario(DateTime(2025, 7, 8), Usuario(login: 'henrique08', senha: 'senha08', nome: 'Henrique Araújo'), 'Gosta de astronomia', 'Mapa celeste luminosa'),
  Aniversario(DateTime(2025, 7, 9), Usuario(login: 'isadora09', senha: 'senha09', nome: 'Isadora Luz'), 'Curte teatro musical', 'Ingressos para espetáculo'),
  Aniversario(DateTime(2025, 7, 10), Usuario(login: 'joao10', senha: 'senha10', nome: 'João Carvalho'), 'Fã de carros antigos', 'Miniatura de Opala SS'),
  Aniversario(DateTime(2025, 7, 11), Usuario(login: 'karla11', senha: 'senha11', nome: 'Karla Silva'), 'Ama jardinagem', 'Sementes exóticas'),
  Aniversario(DateTime(2025, 7, 12), Usuario(login: 'leo12', senha: 'senha12', nome: 'Leo Farias'), 'Curte robótica', 'Sensor de movimento para Arduino'),
  Aniversario(DateTime(2025, 7, 13), Usuario(login: 'mariana13', senha: 'senha13', nome: 'Mariana Vasconcelos'), 'Gosta de pintar em tela', 'Conjunto de pincéis'),
  Aniversario(DateTime(2025, 7, 14), Usuario(login: 'nicolas14', senha: 'senha14', nome: 'Nicolas Peixoto'), 'Fã de tecnologia', 'Mouse ergonômico RGB'),
  Aniversario(DateTime(2025, 7, 15), Usuario(login: 'olivia15', senha: 'senha15', nome: 'Olívia Diniz'), 'Ama esportes radicais', 'Boné de escalada'),
  Aniversario(DateTime(2025, 7, 16), Usuario(login: 'pedro16', senha: 'senha16', nome: 'Pedro Rios'), 'Gosta de café', 'Coador V60'),
  Aniversario(DateTime(2025, 7, 17), Usuario(login: 'quiteria17', senha: 'senha17', nome: 'Quitéria Nogueira'), 'Fã de artesanato', 'Kit para macramê'),
  Aniversario(DateTime(2025, 7, 18), Usuario(login: 'rafael18', senha: 'senha18', nome: 'Rafael Barreto'), 'Curte skate', 'Rodas novas'),
  Aniversario(DateTime(2025, 7, 19), Usuario(login: 'sofia19', senha: 'senha19', nome: 'Sofia Almeida'), 'Ama música clássica', 'Playlist personalizada e fones'),
  Aniversario(DateTime(2025, 7, 20), Usuario(login: 'thiago20', senha: 'senha20', nome: 'Thiago Moreira'), 'Fã de aviação', 'Livro técnico sobre aeronaves'),
  Aniversario(DateTime(2025, 7, 21), Usuario(login: 'ursula21', senha: 'senha21', nome: 'Úrsula Silveira'), 'Curte astrologia', 'Colar com signo personalizado'),
  Aniversario(DateTime(2025, 7, 22), Usuario(login: 'vitor22', senha: 'senha22', nome: 'Vítor Ramos'), 'Ama basquete', 'Bola oficial da NBA'),
  Aniversario(DateTime(2025, 7, 23), Usuario(login: 'wanda23', senha: 'senha23', nome: 'Wanda Freitas'), 'Gosta de gatos pretos', 'Almofada com estampa felina'),
  Aniversario(DateTime(2025, 7, 24), Usuario(login: 'xande24', senha: 'senha24', nome: 'Xande Ferreira'), 'Fã de mecânica', 'Chave ajustável premium'),
  Aniversario(DateTime(2025, 7, 25), Usuario(login: 'yasmin25', senha: 'senha25', nome: 'Yasmin Teixeira'), 'Curte mochilão', 'Mochila dobrável'),
  Aniversario(DateTime(2025, 7, 26), Usuario(login: 'zeca26', senha: 'senha26', nome: 'Zeca Costa'), 'Gosta de blues', 'Harmônica de bolso'),
  Aniversario(DateTime(2025, 7, 27), Usuario(login: 'aline27', senha: 'senha27', nome: 'Aline Prado'), 'Ama podcasts', 'Assinatura de app premium'),
  Aniversario(DateTime(2025, 7, 28), Usuario(login: 'brenda28', senha: 'senha28', nome: 'Brenda Soares'), 'Fã de história medieval', 'Livro ilustrado sobre castelos'),
  Aniversario(DateTime(2025, 7, 29), Usuario(login: 'caio29', senha: 'senha29', nome: 'Caio Fernandes'), 'Curte drones', 'Protetor de hélice'),
  Aniversario(DateTime(2025, 7, 30), Usuario(login: 'daniela30', senha: 'senha30', nome: 'Daniela Luz'), 'Ama yoga', 'Faixa elástica de alongamento'),
  Aniversario(DateTime(2025, 7, 31), Usuario(login: 'eduardo31', senha: 'senha31', nome: 'Eduardo Campos'), 'Gosta de música indie', 'Vinil de Arctic Monkeys'),
  Aniversario(DateTime(2025, 9, 1), Usuario(login: 'ana01', senha: 'senha01', nome: 'Ana Costa'), 'Ama fotografia analógica', 'Filme fotográfico'),
  Aniversario(DateTime(2025, 9, 2), Usuario(login: 'bruno02', senha: 'senha02', nome: 'Bruno Almeida'), 'Curte videogames retrô', 'Console retro portátil'),
  Aniversario(DateTime(2025, 9, 3), Usuario(login: 'carla03', senha: 'senha03', nome: 'Carla Souza'), 'Fã de moda vintage', 'Camisa retrô'),
  Aniversario(DateTime(2025, 9, 4), Usuario(login: 'davi04', senha: 'senha04', nome: 'Davi Pinto'), 'Ama corridas de rua', 'Tênis de corrida'),
  Aniversario(DateTime(2025, 9, 5), Usuario(login: 'elena05', senha: 'senha05', nome: 'Elena Farias'), 'Curte cerâmica', 'Kit para modelagem em argila'),
  Aniversario(DateTime(2025, 9, 6), Usuario(login: 'fabio06', senha: 'senha06', nome: 'Fábio Souza'), 'Ama acampamento', 'Barraca de camping'),
  Aniversario(DateTime(2025, 9, 7), Usuario(login: 'giovana07', senha: 'senha07', nome: 'Giovana Almeida'), 'Curte literatura fantástica', 'Livro “O Senhor dos Anéis”'),
  Aniversario(DateTime(2025, 9, 8), Usuario(login: 'henrique08', senha: 'senha08', nome: 'Henrique Santos'), 'Fã de esportes aquáticos', 'Equipamento de mergulho'),
  Aniversario(DateTime(2025, 9, 9), Usuario(login: 'isadora09', senha: 'senha09', nome: 'Isadora Lopes'), 'Gosta de tricô', 'Blusa de lã feita à mão'),
  Aniversario(DateTime(2025, 9, 10), Usuario(login: 'joao10', senha: 'senha10', nome: 'João Costa'), 'Fã de história medieval', 'Livro sobre castelos medievais'),
  Aniversario(DateTime(2025, 9, 11), Usuario(login: 'karla11', senha: 'senha11', nome: 'Karla Tavares'), 'Gosta de astronomia', 'Binóculos astronômicos'),
  Aniversario(DateTime(2025, 9, 12), Usuario(login: 'leo12', senha: 'senha12', nome: 'Leo Oliveira'), 'Ama desenho digital', 'Mesa digitalizadora'),
  Aniversario(DateTime(2025, 9, 13), Usuario(login: 'mariana13', senha: 'senha13', nome: 'Mariana Nunes'), 'Curte culinária italiana', 'Kit para fazer massas'),
  Aniversario(DateTime(2025, 9, 14), Usuario(login: 'nicolas14', senha: 'senha14', nome: 'Nicolas Martins'), 'Fã de escalada', 'Kit de escalada'),
  Aniversario(DateTime(2025, 9, 15), Usuario(login: 'olivia15', senha: 'senha15', nome: 'Olívia Barbosa'), 'Ama literatura clássica', 'Coleção de livros de Shakespeare'),
  Aniversario(DateTime(2025, 9, 16), Usuario(login: 'pedro16', senha: 'senha16', nome: 'Pedro Ferreira'), 'Fã de futebol', 'Camiseta do time de coração'),
  Aniversario(DateTime(2025, 9, 17), Usuario(login: 'quiteria17', senha: 'senha17', nome: 'Quitéria Souza'), 'Curte jardinagem', 'Planta suculenta em vaso decorativo'),
  Aniversario(DateTime(2025, 9, 18), Usuario(login: 'rafael18', senha: 'senha18', nome: 'Rafael Costa'), 'Fã de hip hop', 'Fones de ouvido com cancelamento de ruído'),
  Aniversario(DateTime(2025, 9, 19), Usuario(login: 'sofia19', senha: 'senha19', nome: 'Sofia Almeida'), 'Ama yoga', 'Bolsa para yoga'),
  Aniversario(DateTime(2025, 9, 20), Usuario(login: 'thiago20', senha: 'senha20', nome: 'Thiago Lima'), 'Gosta de arte urbana', 'Grafiteiro em spray'),
  Aniversario(DateTime(2025, 9, 21), Usuario(login: 'ursula21', senha: 'senha21', nome: 'Úrsula Souza'), 'Curte esportes radicais', 'Camiseta de trilha'),
  Aniversario(DateTime(2025, 9, 22), Usuario(login: 'vitor22', senha: 'senha22', nome: 'Vítor Pereira'), 'Ama cozinhar', 'Kit de facas de chef'),
  Aniversario(DateTime(2025, 9, 23), Usuario(login: 'wanda23', senha: 'senha23', nome: 'Wanda Costa'), 'Fã de jazz', 'Coleção de CDs de jazz'),
  Aniversario(DateTime(2025, 9, 24), Usuario(login: 'xande24', senha: 'senha24', nome: 'Xande Oliveira'), 'Gosta de fazer cerveja artesanal', 'Kit para fazer cerveja em casa'),
  Aniversario(DateTime(2025, 9, 25), Usuario(login: 'yasmin25', senha: 'senha25', nome: 'Yasmin Ferreira'), 'Ama viajar', 'Mapa-múndi para raspar'),
  Aniversario(DateTime(2025, 9, 26), Usuario(login: 'zeca26', senha: 'senha26', nome: 'Zeca Tavares'), 'Curte acampamento', 'Lanterna de camping'),
  Aniversario(DateTime(2025, 9, 27), Usuario(login: 'aline27', senha: 'senha27', nome: 'Aline Pereira'), 'Ama ciclismo', 'Capacete de ciclismo'),
  Aniversario(DateTime(2025, 9, 28), Usuario(login: 'brenda28', senha: 'senha28', nome: 'Brenda Lima'), 'Fã de cinema de terror', 'Assinatura de streaming de filmes de terror'),
  Aniversario(DateTime(2025, 9, 29), Usuario(login: 'caio29', senha: 'senha29', nome: 'Caio Souza'), 'Gosta de fazer churrasco', 'Conjunto de espetos'),
  Aniversario(DateTime(2025, 9, 30), Usuario(login: 'daniela30', senha: 'senha30', nome: 'Daniela Alves'), 'Ama leitura de ficção', 'Assinatura de clube de livros'),
  Aniversario(DateTime(2025, 10, 1), Usuario(login: 'ana01', senha: 'senha01', nome: 'Ana Costa'), 'Ama pintura em aquarela', 'Kit de aquarelas profissionais'),
  Aniversario(DateTime(2025, 10, 2), Usuario(login: 'bruno02', senha: 'senha02', nome: 'Bruno Oliveira'), 'Curte música clássica', 'Assinatura de streaming de música clássica'),
  Aniversario(DateTime(2025, 10, 3), Usuario(login: 'carla03', senha: 'senha03', nome: 'Carla Martins'), 'Fã de culinária vegana', 'Cesta de produtos veganos'),
  Aniversario(DateTime(2025, 10, 4), Usuario(login: 'davi04', senha: 'senha04', nome: 'Davi Souza'), 'Gosta de skate', 'Skate de madeira'),
  Aniversario(DateTime(2025, 10, 5), Usuario(login: 'elena05', senha: 'senha05', nome: 'Elena Rocha'), 'Curte escalada', 'Cordas para escalada'),
  Aniversario(DateTime(2025, 10, 6), Usuario(login: 'fabio06', senha: 'senha06', nome: 'Fábio Nunes'), 'Fã de vinho', 'Kit de degustação de vinhos'),
  Aniversario(DateTime(2025, 10, 7), Usuario(login: 'giovana07', senha: 'senha07', nome: 'Giovana Santos'), 'Ama fotografia de rua', 'Câmera fotográfica digital'),
  Aniversario(DateTime(2025, 10, 8), Usuario(login: 'henrique08', senha: 'senha08', nome: 'Henrique Almeida'), 'Curte história medieval', 'Coleção de miniaturas de cavaleiros'),
  Aniversario(DateTime(2025, 10, 9), Usuario(login: 'isadora09', senha: 'senha09', nome: 'Isadora Lima'), 'Ama cozinhar sobremesas', 'Kit de utensílios para bolos'),
  Aniversario(DateTime(2025, 10, 10), Usuario(login: 'joao10', senha: 'senha10', nome: 'João Costa'), 'Fã de videogames', 'Console de videogame de última geração'),
  Aniversario(DateTime(2025, 10, 11), Usuario(login: 'karla11', senha: 'senha11', nome: 'Karla Alves'), 'Ama jardinagem', 'Kit para cultivo de plantas'),
  Aniversario(DateTime(2025, 10, 12), Usuario(login: 'leo12', senha: 'senha12', nome: 'Leo Pereira'), 'Curte cinema independente', 'Ingressos para festival de cinema'),
  Aniversario(DateTime(2025, 10, 13), Usuario(login: 'mariana13', senha: 'senha13', nome: 'Mariana Oliveira'), 'Fã de séries', 'Assinatura de streaming de séries'),
  Aniversario(DateTime(2025, 10, 14), Usuario(login: 'nicolas14', senha: 'senha14', nome: 'Nicolas Barbosa'), 'Gosta de arte contemporânea', 'Ingressos para exposição de arte'),
  Aniversario(DateTime(2025, 10, 15), Usuario(login: 'olivia15', senha: 'senha15', nome: 'Olívia Gomes'), 'Fã de literatura de suspense', 'Livro de Agatha Christie'),
  Aniversario(DateTime(2025, 10, 16), Usuario(login: 'pedro16', senha: 'senha16', nome: 'Pedro Farias'), 'Curte arte digital', 'Tablet de desenho gráfico'),
  Aniversario(DateTime(2025, 10, 17), Usuario(login: 'quiteria17', senha: 'senha17', nome: 'Quitéria Silva'), 'Ama esportes ao ar livre', 'Kit para trilhas ecológicas'),
  Aniversario(DateTime(2025, 10, 18), Usuario(login: 'rafael18', senha: 'senha18', nome: 'Rafael Costa'), 'Fã de fotografia de natureza', 'Câmera fotográfica profissional'),
  Aniversario(DateTime(2025, 10, 19), Usuario(login: 'sofia19', senha: 'senha19', nome: 'Sofia Tavares'), 'Ama costura', 'Máquina de costura portátil'),
  Aniversario(DateTime(2025, 10, 20), Usuario(login: 'thiago20', senha: 'senha20', nome: 'Thiago Almeida'), 'Gosta de esportes radicais', 'Prancha de surf'),
  Aniversario(DateTime(2025, 10, 21), Usuario(login: 'ursula21', senha: 'senha21', nome: 'Úrsula Souza'), 'Fã de ciclismo', 'Bicicleta de estrada'),
  Aniversario(DateTime(2025, 10, 22), Usuario(login: 'vitor22', senha: 'senha22', nome: 'Vítor Lima'), 'Ama esportes de inverno', 'Casaco térmico'),
  Aniversario(DateTime(2025, 10, 23), Usuario(login: 'wanda23', senha: 'senha23', nome: 'Wanda Costa'), 'Fã de literatura histórica', 'Coleção de livros sobre a Segunda Guerra Mundial'),
  Aniversario(DateTime(2025, 10, 24), Usuario(login: 'xande24', senha: 'senha24', nome: 'Xande Martins'), 'Ama filmes de terror', 'Coleção de filmes de terror clássico'),
  Aniversario(DateTime(2025, 10, 25), Usuario(login: 'yasmin25', senha: 'senha25', nome: 'Yasmin Almeida'), 'Gosta de fazer tricô', 'Lãs e agulhas de tricô'),
  Aniversario(DateTime(2025, 10, 26), Usuario(login: 'zeca26', senha: 'senha26', nome: 'Zeca Souza'), 'Curte música eletrônica', 'Fones de ouvido Bluetooth'),
  Aniversario(DateTime(2025, 10, 27), Usuario(login: 'aline27', senha: 'senha27', nome: 'Aline Lima'), 'Fã de cultura japonesa', 'Kimono tradicional japonês'),
  Aniversario(DateTime(2025, 10, 28), Usuario(login: 'brenda28', senha: 'senha28', nome: 'Brenda Oliveira'), 'Ama fazer arte com papel', 'Kit de scrapbooking'),
  Aniversario(DateTime(2025, 10, 29), Usuario(login: 'caio29', senha: 'senha29', nome: 'Caio Rocha'), 'Gosta de vinho', 'Conjunto de taças de vinho'),
  Aniversario(DateTime(2025, 10, 30), Usuario(login: 'daniela30', senha: 'senha30', nome: 'Daniela Nunes'), 'Fã de jardinagem urbana', 'Kit de plantas para apartamento'),
  Aniversario(DateTime(2025, 10, 31), Usuario(login: 'eduardo31', senha: 'senha31', nome: 'Eduardo Ferreira'), 'Gosta de filmes de terror', 'Assinatura de streaming de filmes de terror'),
  Aniversario(DateTime(2025, 11, 1), Usuario(login: 'ana01', senha: 'senha01', nome: 'Ana Silva'), 'Ama caminhar na natureza', 'Botas de trilha'),
  Aniversario(DateTime(2025, 11, 2), Usuario(login: 'bruno02', senha: 'senha02', nome: 'Bruno Costa'), 'Curte música indie', 'Vinil da banda favorita'),
  Aniversario(DateTime(2025, 11, 3), Usuario(login: 'carla03', senha: 'senha03', nome: 'Carla Lima'), 'Fã de filmes de ação', 'Assinatura de streaming de filmes'),
  Aniversario(DateTime(2025, 11, 4), Usuario(login: 'davi04', senha: 'senha04', nome: 'Davi Oliveira'), 'Gosta de futebol', 'Camiseta do time'),
  Aniversario(DateTime(2025, 11, 5), Usuario(login: 'elena05', senha: 'senha05', nome: 'Elena Martins'), 'Ama cozinhar', 'Kit de utensílios de cozinha'),
  Aniversario(DateTime(2025, 11, 6), Usuario(login: 'fabio06', senha: 'senha06', nome: 'Fábio Tavares'), 'Curte ciclismo de estrada', 'Bicicleta nova'),
  Aniversario(DateTime(2025, 11, 7), Usuario(login: 'giovana07', senha: 'senha07', nome: 'Giovana Farias'), 'Fã de teatro', 'Ingressos para peça de teatro'),
  Aniversario(DateTime(2025, 11, 8), Usuario(login: 'henrique08', senha: 'senha08', nome: 'Henrique Souza'), 'Curte arte digital', 'Software de edição de imagens'),
  Aniversario(DateTime(2025, 11, 9), Usuario(login: 'isadora09', senha: 'senha09', nome: 'Isadora Rocha'), 'Fã de séries de suspense', 'Assinatura de streaming'),
  Aniversario(DateTime(2025, 11, 10), Usuario(login: 'joao10', senha: 'senha10', nome: 'João Santos'), 'Ama videogames', 'Console de videogame de última geração'),
  Aniversario(DateTime(2025, 11, 11), Usuario(login: 'karla11', senha: 'senha11', nome: 'Karla Almeida'), 'Fã de arquitetura', 'Livro sobre arquitetura clássica'),
  Aniversario(DateTime(2025, 11, 12), Usuario(login: 'leo12', senha: 'senha12', nome: 'Leo Costa'), 'Curte caminhar na praia', 'Camiseta de praia'),
  Aniversario(DateTime(2025, 11, 13), Usuario(login: 'mariana13', senha: 'senha13', nome: 'Mariana Oliveira'), 'Fã de culinária internacional', 'Livro de receitas gourmet'),
  Aniversario(DateTime(2025, 11, 14), Usuario(login: 'nicolas14', senha: 'senha14', nome: 'Nicolas Silva'), 'Ama filmes clássicos', 'Coleção de filmes clássicos em DVD'),
  Aniversario(DateTime(2025, 11, 15), Usuario(login: 'olivia15', senha: 'senha15', nome: 'Olívia Souza'), 'Curte praticar yoga', 'Tapete de yoga de alta qualidade'),
  Aniversario(DateTime(2025, 11, 16), Usuario(login: 'pedro16', senha: 'senha16', nome: 'Pedro Farias'), 'Ama skate', 'Skate personalizado'),
  Aniversario(DateTime(2025, 11, 17), Usuario(login: 'quiteria17', senha: 'senha17', nome: 'Quitéria Rocha'), 'Fã de arte contemporânea', 'Assinatura de revista de arte'),
  Aniversario(DateTime(2025, 11, 18), Usuario(login: 'rafael18', senha: 'senha18', nome: 'Rafael Costa'), 'Ama filmes de terror', 'Coleção de filmes de terror'),
  Aniversario(DateTime(2025, 11, 19), Usuario(login: 'sofia19', senha: 'senha19', nome: 'Sofia Lima'), 'Gosta de jardinagem', 'Kit para cultivo de suculentas'),
  Aniversario(DateTime(2025, 11, 20), Usuario(login: 'thiago20', senha: 'senha20', nome: 'Thiago Oliveira'), 'Curte esportes aquáticos', 'Prancha de surf'),
  Aniversario(DateTime(2025, 11, 21), Usuario(login: 'ursula21', senha: 'senha21', nome: 'Úrsula Farias'), 'Fã de fotografia', 'Câmera fotográfica vintage'),
  Aniversario(DateTime(2025, 11, 22), Usuario(login: 'vitor22', senha: 'senha22', nome: 'Vítor Pereira'), 'Curte maratonas de filmes', 'Assinatura de serviço de streaming de filmes'),
  Aniversario(DateTime(2025, 11, 23), Usuario(login: 'wanda23', senha: 'senha23', nome: 'Wanda Souza'), 'Ama fazer tricô', 'Lãs e agulhas especiais'),
  Aniversario(DateTime(2025, 11, 24), Usuario(login: 'xande24', senha: 'senha24', nome: 'Xande Lima'), 'Fã de música eletrônica', 'Fones de ouvido de alta qualidade'),
  Aniversario(DateTime(2025, 11, 25), Usuario(login: 'yasmin25', senha: 'senha25', nome: 'Yasmin Costa'), 'Ama literatura policial', 'Livro de Sherlock Holmes'),
  Aniversario(DateTime(2025, 11, 26), Usuario(login: 'zeca26', senha: 'senha26', nome: 'Zeca Martins'), 'Fã de culinária italiana', 'Kit para fazer pizza em casa'),
  Aniversario(DateTime(2025, 11, 27), Usuario(login: 'aline27', senha: 'senha27', nome: 'Aline Rocha'), 'Gosta de dançar', 'Tênis de dança'),
  Aniversario(DateTime(2025, 11, 28), Usuario(login: 'brenda28', senha: 'senha28', nome: 'Brenda Almeida'), 'Fã de colecionismo', 'Coleção de action figures'),
  Aniversario(DateTime(2025, 11, 29), Usuario(login: 'caio29', senha: 'senha29', nome: 'Caio Souza'), 'Gosta de jardinagem urbana', 'Mini jardim de plantas tropicais'),
  Aniversario(DateTime(2025, 11, 30), Usuario(login: 'daniela30', senha: 'senha30', nome: 'Daniela Tavares'), 'Curte caminhada ao ar livre', 'Mochila para trilha'),
  Aniversario(DateTime(2025, 12, 1), Usuario(login: 'ana01', senha: 'senha01', nome: 'Ana Silva'), 'Ama caminhadas ao ar livre', 'Botas de caminhada'),
  Aniversario(DateTime(2025, 12, 2), Usuario(login: 'bruno02', senha: 'senha02', nome: 'Bruno Costa'), 'Curte música clássica', 'Partitura de piano'),
  Aniversario(DateTime(2025, 12, 3), Usuario(login: 'carla03', senha: 'senha03', nome: 'Carla Almeida'), 'Fã de culinária italiana', 'Kit para fazer massas'),
  Aniversario(DateTime(2025, 12, 4), Usuario(login: 'davi04', senha: 'senha04', nome: 'Davi Tavares'), 'Ama praticar esportes radicais', 'Kit para escalada'),
  Aniversario(DateTime(2025, 12, 5), Usuario(login: 'elena05', senha: 'senha05', nome: 'Elena Lima'), 'Fã de filmes de ação', 'Assinatura de streaming de filmes'),
  Aniversario(DateTime(2025, 12, 6), Usuario(login: 'fabio06', senha: 'senha06', nome: 'Fábio Silva'), 'Gosta de fotografia', 'Câmera profissional'),
  Aniversario(DateTime(2025, 12, 7), Usuario(login: 'giovana07', senha: 'senha07', nome: 'Giovana Rocha'), 'Ama jardinagem', 'Kit de jardinagem urbano'),
  Aniversario(DateTime(2025, 12, 8), Usuario(login: 'henrique08', senha: 'senha08', nome: 'Henrique Souza'), 'Curte música indie', 'Fone de ouvido Bluetooth'),
  Aniversario(DateTime(2025, 12, 9), Usuario(login: 'isadora09', senha: 'senha09', nome: 'Isadora Nunes'), 'Fã de literatura', 'Coleção de livros clássicos'),
  Aniversario(DateTime(2025, 12, 10), Usuario(login: 'joao10', senha: 'senha10', nome: 'João Oliveira'), 'Gosta de praticar yoga', 'Tapete de yoga'),
  Aniversario(DateTime(2025, 12, 11), Usuario(login: 'karla11', senha: 'senha11', nome: 'Karla Tavares'), 'Ama costura', 'Máquina de costura portátil'),
  Aniversario(DateTime(2025, 12, 12), Usuario(login: 'leo12', senha: 'senha12', nome: 'Leo Costa'), 'Curte história medieval', 'Coleção de miniaturas medievais'),
  Aniversario(DateTime(2025, 12, 13), Usuario(login: 'mariana13', senha: 'senha13', nome: 'Mariana Pereira'), 'Fã de filmes de terror', 'Coleção de DVDs de filmes de terror'),
  Aniversario(DateTime(2025, 12, 14), Usuario(login: 'nicolas14', senha: 'senha14', nome: 'Nicolas Lima'), 'Gosta de videogames', 'Assinatura de jogo digital'),
  Aniversario(DateTime(2025, 12, 15), Usuario(login: 'olivia15', senha: 'senha15', nome: 'Olívia Martins'), 'Ama fotografia de natureza', 'Câmera instantânea'),
  Aniversario(DateTime(2025, 12, 16), Usuario(login: 'pedro16', senha: 'senha16', nome: 'Pedro Almeida'), 'Fã de esportes ao ar livre', 'Mochila de hidratação para trilhas'),
  Aniversario(DateTime(2025, 12, 17), Usuario(login: 'quiteria17', senha: 'senha17', nome: 'Quitéria Costa'), 'Curte culinária vegana', 'Assinatura de caixa de produtos veganos'),
  Aniversario(DateTime(2025, 12, 18), Usuario(login: 'rafael18', senha: 'senha18', nome: 'Rafael Oliveira'), 'Ama arte contemporânea', 'Ingressos para exposição de arte'),
  Aniversario(DateTime(2025, 12, 19), Usuario(login: 'sofia19', senha: 'senha19', nome: 'Sofia Farias'), 'Fã de tricô', 'Kit de fios de lã e agulhas'),
  Aniversario(DateTime(2025, 12, 20), Usuario(login: 'thiago20', senha: 'senha20', nome: 'Thiago Silva'), 'Curte filmes de ficção científica', 'Assinatura de revista de ficção científica'),
  Aniversario(DateTime(2025, 12, 21), Usuario(login: 'ursula21', senha: 'senha21', nome: 'Úrsula Rocha'), 'Fã de astrologia', 'Livros sobre astrologia'),
  Aniversario(DateTime(2025, 12, 22), Usuario(login: 'vitor22', senha: 'senha22', nome: 'Vítor Santos'), 'Gosta de escrever', 'Caderno de couro e caneta de luxo'),
  Aniversario(DateTime(2025, 12, 23), Usuario(login: 'wanda23', senha: 'senha23', nome: 'Wanda Souza'), 'Fã de colecionismo', 'Coleção de action figures'),
  Aniversario(DateTime(2025, 12, 24), Usuario(login: 'xande24', senha: 'senha24', nome: 'Xande Lima'), 'Gosta de viajar', 'Guia de viagens para novos destinos'),
  Aniversario(DateTime(2025, 12, 25), Usuario(login: 'yasmin25', senha: 'senha25', nome: 'Yasmin Costa'), 'Ama fazer arte com papel', 'Kit de scrapbooking e carimbos'),
  Aniversario(DateTime(2025, 12, 26), Usuario(login: 'zeca26', senha: 'senha26', nome: 'Zeca Pereira'), 'Fã de música rock', 'Coleção de vinis de rock clássico'),
  Aniversario(DateTime(2025, 12, 27), Usuario(login: 'aline27', senha: 'senha27', nome: 'Aline Lima'), 'Gosta de esportes aquáticos', 'Prancha de surf'),
  Aniversario(DateTime(2025, 12, 28), Usuario(login: 'brenda28', senha: 'senha28', nome: 'Brenda Farias'), 'Ama artesanato', 'Kit de pintura em tecido'),
  Aniversario(DateTime(2025, 12, 29), Usuario(login: 'caio29', senha: 'senha29', nome: 'Caio Oliveira'), 'Curte fotografia artística', 'Lentes para câmera fotográfica'),
  Aniversario(DateTime(2025, 12, 30), Usuario(login: 'daniela30', senha: 'senha30', nome: 'Daniela Costa'), 'Ama esportes radicais', 'Equipamento de snowboard'),
  Aniversario(DateTime(2025, 12, 31), Usuario(login: 'eduardo31', senha: 'senha31', nome: 'Eduardo Nunes'), 'Fã de tecnologia', 'Gadgets de última geração'),
  
  ];
  
  static adicionarAniversario(Aniversario aniversario){
    AniversarioList.lista.add(aniversario);
    }
  static removerAniversario(Aniversario aniversario){
        AniversarioList.lista.removeWhere((niver)=>niver.usuario.nome == (aniversario.usuario.nome) && niver.detalhes == aniversario.detalhes && aniversario.data == niver.data);
  }
  static List <Aniversario> getProximosAniversarios(){
    List <Aniversario> lista= List.from(
      AniversarioList.lista.where(
        (a)=>(a.data.month.compareTo(DateTime.now().month) == 0 
        && a.data.day.compareTo(DateTime.now().day) >= 0 ) ||a.data.month.compareTo(DateTime.now().month) >0
      )
    );
    lista.sort((a,b)=>a.data.compareTo(b.data));
    return lista;
  }
  static List <Aniversario> filtrarAniversariosPorNome(String nome){
      List <Aniversario> lista = List.from(
    AniversarioList.lista.where(
    (a) =>a.usuario.nome.contains(nome))
    );
    return lista;
  }
  static List<Aniversario> filtrarAniversariosPorDataENome(DateTime data,String nome){
    List <Aniversario> lista = List.from(
      AniversarioList.lista.where(
      (a) => a.data.month.compareTo(data.month).isEven && a.data.day.compareTo(data.day).isEven
      )
    );
    lista = List.from(
    lista.where(
    (a) =>a.usuario.nome.contains(nome))
    );
    return lista;
  }
  static bool mesmaData(DateTime data1, DateTime data2) {
  return data1.year == data2.year &&
         data1.month == data2.month &&
         data1.day == data2.day;
}
}